### ISSUE TITLE
Improve queryability of donor import failures

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1005]
As a support agent/admin,
I want to know which donors failed to import and why
so that I can either re-submit the donor update or accept the failure, e.g., validation error caused by missing DRB1 typing.

**Description**
Donor import failures are already logged to Application Insights, however, it is not ideal for querying failures that may have happened several weeks ago, or when there are lots of failures and AI sampling may be applied.

The large volume of donor failures that have been observed in WMDA prod (some of which have lead to discrepancies in search results between Atlas and HAP-E) warrants an enhancement to how failure information is logged to make it as queryable as possible, even weeks after the failure occurred.

WMDA have requested that failures are logged to a table that can be easily queried and that failures be coded so they can be grouped by type.

**Component(s) to enhance (if known)**
- Donor Import

**Business value (select one or more):**
- Improved supportability

**How would this enhancement provide this value?**
Improved failure queryability will ensure that all donors that should be in Atlas are actually in Atlas.

**Acceptance Criteria**
Given a donor import file with one or more invalid donor updates,
When the file is uploaded to Atlas,
Then a new row should be added to the donor import failure table, one for each invalid update, with relevant details of why each donor failed to be imported.

**Required By Date (if any)**
Before full load of donors into new instance of Atlas.

**Comment by zabeen** [comment]
### HLD

- New table to be defined in `Atlas.DonorImport.Data`: `DonorImportFailures`
  - Columns:
    - `ExternalDonorCode` string
    - `UpdateFile` string (i.e., name of the donor file)
    - `FailureCode` enum - compile a list of enum values by looking through the existing donor import code and identifying the expected reasons for update failure, e.g., incorrect schema, validation failure, etc.
    - `FailureReason` string 
    - `FailureTime` DateTimeOffset
  
- A new row should be added to the table whenever a donor update is rejected in the code (e.g., during deserialization, validation, etc).
  - An easy way to find all such places is to look for whenever we send a import failure event to AI.

**Comment by zabeen** [comment]
@mmelchers FYI, please let me know if this looks right, or if you need anything extra, thanks!

**Comment by zabeen** [comment]
@mmelchers we need to add a job to delete "old" failure information (I'll raise a new ticket for that), what should the default period of expiry be? We can make it configurable, but is a default of 2 months ok?

**Comment by mmelchers** [comment]
@zabeen this looks good. 2 months expiry should be fine.

**Comment by zabeen** [comment]
### Design Notes

- @disaev-nmdp looked into donor import code, and the only cause for individual donor update failures is validation failure (deserialization failures cause the entire file to fail).
- On that basis, the `FailureCode` field has been deemed no longer useful, as wording of validation errors is consistent (it is auto-generated by `FluentValidation` library) and so can be used for querying or grouping errors.
- If this changes in future, then adding the code field to the table should be a simple, non-breaking enhancement.
- If a donor update has multiple validation errors, then one row will be written for every unique error.

**Comment by zabeen** [comment]
### Testing Notes

- Shared database should have new table, `Donors.DonorImportFailures`.

Given a donor import file with one valid donor update, and one invalid update (missing DRB1),
When the file is uploaded to Atlas blob storage
Then the import should complete successfully overall (i.e., success notification should be sent out)
And only the valid donor update should have been added to the donor store
And the invalid donor update should be recorded in `DonorImportFailures` along with the reason for failure (missing DRB1).

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok
<img width="626" alt="Screenshot at Jul 12 12-43-49" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/c1904e00-bc6f-4693-bcc8-47ee04742399">
<img width="372" alt="Screenshot at Jul 12 12-45-26" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/d667b98f-c7fb-4bf7-838a-019195551e54">

**Comment by zabeen** [comment]
@DmitriyShcherbina wonderful, thanks! I assume `EthnicityCode` is meant to be `null` as it was empty in original file?

**Comment by DmitriyShcherbina** [comment]
@zabeen Yep, you right!
