### ISSUE TITLE
values for scoring results do not seem to be correct

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#1011]
**Describe the bug**
When looking at scoringResults in a search result, the data does not seem to be correct: 
example from search 00e51cfa-c62a-4d40-a8b1-f8a4a9b53c90 on wmda dev instance

"TotalMatchCount": 1,
            "MatchCategory": "PermissiveMismatch",
            "GradeScore": 0,
            "ConfidenceScore": 0,
            "TypedLociCountAtScoredLoci": 1,
            "PotentialMatchCount": 0,
            "ExactMatchCount": 1,

**To Reproduce**
Start search. turn on scoring for all loci

check search results
**Expected behaviour**
match category , potentialmatchcount and exactmatchcount are correct
**Screenshots**

**Inputs/Outputs**
E.g., donor input file, body of search request, search results file, body of service bus message, etc.

**Atlas Build & Runtime Info (please complete the following information):**
 - Runtime Environment [e.g. local Windows desktop, Azure cloud]
 - Atlas Version [e.g. 1.0.0]
 - GitHub commit ID of Atlas build

**Additional context**
Is a blocker for implementing scoring based match class determination!!!!!

**Comment by zabeen** [comment]
@mmelchers I'll investigate this next week when I look into #651 and #996

**Comment by zabeen** [comment]
Hi @mmelchers ( FYI @WMDAJesse )

The search request for `00e51cfa-c62a-4d40-a8b1-f8a4a9b53c90` only included DPB1 for scoring, not all loci:

```
"ScoringCriteria": {
            "LociToScore": [
                "Dpb1"
            ],
            "LociToExcludeFromAggregateScore": []
        },
```

That maybe why the result was not as you expected, as it seems you expected scoring to be enabled at all loci.

On that basis, I am closing this ticket. We still have the issue of match grades being arbitrarily assigned, and so I will focus on that.
