### ISSUE TITLE
Orientate positional scores to donor typing

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1012]
Positional scores are currently orientated to patient typing, but it makes more sense for them to be aligned to donor typing - and that is the expectation from WMDA (current AN search implementation does not care about the orientation; it does not show this data to users, only the overall grade/match count).

**Comment by zabeen** [comment]
### AN Testing Notes

This change can only be regression tested on AN - it needs more thorough testing on WMDA, where the issue was first reported.

Regression test:
- Run a 10/10 search with scoring requested at all loci, Dpb1 excluded from aggregation, and match prediction ON.
- For each locus in `ScoringResult.ScoringResultsByLocus`:
  - Every property within `ScoreDetailsAtPositionOne` and `ScoreDetailsAtPositionTwo` should be non-null.

**Comment by DmitriyShcherbina** [comment]
@zabeen It looks ok from my perspective
"searchIdentifier": "163fd602-eeba-4413-a32e-b3f03e2baae0"
<img width="323" alt="image" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/e5450dd2-2c37-4ad6-9163-f33f69a4f3bc">

**Comment by zabeen** [comment]
### WMDA Testing

Once the change has been deployed to WMDA Dev, need to re-run search `8956421b-8305-463b-ac26-eea97db1350a`, and check orientation of `DRB1` scores on donors `267964142` and `267967416`. Position 2 should be called mismatch.

If that looks good, then release to Prod and re-run searches raised by super-users (will need search IDs for this).
