### ISSUE TITLE
Debug endpoint for imputation (a.k.a. "genotype expansion")

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1021]
New debug endpoint on match prediction functions app that takes in a HLA typing, ethnicity and registry code, and returns a list of genotypes.

Recommend returning the truncated list, as that is the one used in match calculation.

May involve some minor refactoring of the match probability service.

**Comment by zabeen** [comment]
### Regression Testing

- run a 10/10 search with match predicition ON
- check search results have match prediction results
- search AI logs by search request ID and check the following entries are still being written:
  - "Match prediction: Expand patient phenotype"
  - "Match prediction: Expand patient genotype"
  - "Match prediction: Calculate likelihoods for genotypes"

**Comment by DmitriyShcherbina** [comment]
@zabeen I've run 10/10 search and results look ok, they have match prediction results
But could you please help with AI logs request to check listed entries?
I've tried this request saved in DEV-ATLAS, but I haven't found listed entries:
```
let searchRequestId = "ce38f47b-ef9f-47ac-8b3d-817e2b6ea166";
let invocationIds =
union traces
| union exceptions
| union customEvents
| where customDimensions["SearchRequestId"] == searchRequestId
| project invocationId = tostring(customDimensions["InvocationId"])
| summarize by invocationId;
union traces
| union exceptions
| union customEvents
| where tostring(customDimensions["InvocationId"]) in (invocationIds)
| project timestamp, itemType, operation_Name, message = case(itemType == "customEvent", name, itemType == "exception", strcat(outerMessage," - ",innermostMessage), message), customDimensions, invocationId = tostring(customDimensions["InvocationId"])
| order by invocationId, timestamp desc
```


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/844effd7-d93c-449d-b170-3b0c40e1d8be)

**Comment by zabeen** [comment]
@DmitriyShcherbina I looked at 2 searches from before this change was merged, and neither had those particular trace messages logged, so it's an ongoing issue not caused by this ticket. I will raise a new ticket for it.
