### ISSUE TITLE
Incorrect DPB1 TCE3 match grading

### ISSUE THREAD

**Issue by RimkePostel** [Anthony-Nolan/Atlas#1028]
**Issue**
DPB1 permissiveness is currently shown incorrectly. Donors with a DPB1\*04:01:01G or DPB1\*01:01:01G typing are scored as ambiguous when they should be scored as non-permissive (in either GvH or HvG direction) or permissive. We were experiencing similar issues with Hap-E. The Hap-E developers found that this issue resulted from the new HLA release 3.53.0 where several rare alleles got a new TCE assignment. 

**To Reproduce**
1. Go to Search&Match
2. Add a patient with DPB1\*01:01:01 and DPB1\*04:01:01 alleles
3. Several donors will be returned as ambiguous when they should be returned as permissive or non-permissive

**Expected behaviour**
We expect the DPB1 match grade permissiveness to match with the permissiveness that is calculated by the [IMGT/HLA DPB1 T-Cell Epitope Algorithm](https://www.ebi.ac.uk/ipd/imgt/hla/matching/dpb_v2/).

**Screenshots**
![ATLAS_DPB1Perm_1](https://github.com/Anthony-Nolan/Atlas/assets/141727021/51926f0f-04bd-41f7-9567-336dbcfafa2b)
![ATLAS_DPB1Perm_2](https://github.com/Anthony-Nolan/Atlas/assets/141727021/8dbf802f-a4f0-4cb8-84c5-ef213618eef3)
![ATLAS_DPB1Perm_3](https://github.com/Anthony-Nolan/Atlas/assets/141727021/7db1243b-8d47-4100-8082-1c70931d7fa4)

**Additional context**
For example case, see:
search id  = d6304d8b-e880-4ca0-ac5c-2ae67df94129
donor ids: 
377449095
377458494

**Comment by RimkePostel** [comment]
Hi @zabeen ,

As requested I am sending you additional information about how the Hap-E developers have fixed this issue:

Since the new HLA release 3.53.0 the allele DPB1*1148:01 of G group DPB1*04:01:01G and DPB1*1038:01 of G group DPB1*01:01:01G has the TCE group assignment 1 (before it was unassigned).
Thus, the TCE group assignment for G group DPB1*04:01:01G and DPB1*01:01:01 would no longer be unique (group 1 and 3), which led to the ambiguous score (‘X’) in Hap-E search results.

We consider this to be an error in the data basis of HLA release 3.53.0 and have corrected it so that both G Groups again has the unique TCE group assignment 3.

Thus, Hap-E now behaves again like the IPD-IMGT/HLA.


P.S: Screenshots to IMGTHLA data:
![Picture1](https://github.com/Anthony-Nolan/Atlas/assets/141727021/3d0a047f-0b8f-46f8-880e-c5133640c28e)

![Picture2](https://github.com/Anthony-Nolan/Atlas/assets/141727021/591b4e36-b73d-425d-99d0-4d72240a473f)

![Picture3](https://github.com/Anthony-Nolan/Atlas/assets/141727021/88eb527a-ebda-4e8a-a3a2-e0366b439ad8)

**Comment by zabeen** [comment]
## Solution

The issue has been resolved on both UAT and LIVE-WMDA-ATLAS as follows.

### Fix
I manually edited the assigned TCE group for the following DPB1* typings in v3.53.0 of the Atlas HLA metadata dictionary, from `1` to `3`:

- 1148:01, 1148:01Q, 1148:XX

- 1038:01, 1038:01Q, 1038:XX

I then manually refreshed the matching algorithm cache to propagate the changes.

### Testing
Using the patients listed above, I ran “before” and “after” searches, and observed the following results which are in line with the expectations listed in the ticket description:

Patient 1) 01:01:01, 04:01:01
Donor 35512717 - 04:01:01G, 16:01:01G - Unknown -> PermissiveMismatch
Donor 26911245 - 01:01:01G, 16:01:01 - Unknown -> PermissiveMismatch
Donor 31594122 - 01:01:01G, 02:01:02 - Unknown -> PermissiveMismatch

Patient 2) 04:01, 04:01
Donor 957424 - 1:CMVHN, 04:CMVHV- Unknown -> PermissiveMismatch
Donor 7900072 - 01:01:01G, 10:01:01 - Unknown -> Mismatch, NonPermissiveHvG

Patient 3) 01:01, 04:01
Donor 350221 - 04:01:01G, 13:01:01G - Unknown -> PermissiveMismatch
Donor 984775 - 04:01:01G, 06:01:01G - Unknown -> Mismatch, NonPermissiveHvG


### Risks
- On next release of the IMGT/HLA database (scheduled to be in approx. 2 months), if the above alleles still have TCE group of 1 assigned, then the manual data fix will need to be reapplied after the data refresh job completes.

**Comment by RimkePostel** [comment]
Hi @zabeen, I checked my searches: the issue has been resolved! Thanks a lot :)
