### ISSUE TITLE
Add property to FailureInfo containing failure message

### ISSUE THREAD

**Issue by daria-sorokina-da** [Anthony-Nolan/Atlas#1033]
Currently if match prediction stage of the algorithm does not fail, and failure happens at a later stage, FailureInfo does not contain a failure message, see example:
```
{
"FailureMessage": "Search failed at stage: PersistSearchResults. See Application Insights for failure details.",
"FailureInfo": {
   "StageReached": "PersistSearchResults",
   "MatchingAlgorithmFailureInfo": null,
   "WillRetry": false
},
"MatchingAlgorithmTime": "00:00:00",
"MatchPredictionTime": "00:00:00",
"OverallSearchTime": "00:00:00",
"SearchRequestId": "2fdbf2e0-7001-4ae1-b3a7-b37ad713c26e",
"WasSuccessful": false,
"RepeatSearchRequestId": null,
"BlobStorageContainerName": null,
"ResultsFileName": null,
"NumberOfResults": null,
"MatchingAlgorithmHlaNomenclatureVersion": null,
"ResultsBatched": false,
"BatchFolderName": null
}
```

Here MatchingAlgorithmFailureInfo is null, because the failure happened on a later stage.

Let's add a property FailureMessage / Message to FailureInfo to cover that, i.e. it should contain "Search failed at stage: PersistSearchResults" in this case.

Please note that FailureMessage in the root of this JSON is obsolete, and should be removed in the upcoming releases, as all failure info should be in FailureInfo property.

**Comment by zabeen** [comment]
Design suggestion: new prop, `FailureInfo.Message` could be a function of the other props by [copying this code](https://github.com/Anthony-Nolan/Atlas/blob/efead5b050204299d3da7717c59db335960be661/Atlas.Functions/Services/SearchCompletionMessageSender.cs#L91) into the model.

**Comment by zabeen** [comment]
### Testing

- Run a search with match prediction ON, but with invalid HLA at position A_1 e.g., "invalid-HLA".
  - This should cause the search to fail with a validation error.
- Find search notification in `search-results-ready`:
  - `FailureInfo` should be populated, and a new property should be present: `Summary` which should say something like: `"Search failed at stage: Matching Algorithm, with validation error...[invalid-HLA]"`

#### Regression testing
- run a valid 10/10 search with match prediction ON, ensure it completes successfully.

**Comment by zabeen** [comment]
@WMDAJesse FYI, this [the new prop](https://github.com/Anthony-Nolan/Atlas/blob/f891ab775af2051e50815ea6ebeaf2c46e037a30/Atlas.Client.Models/Search/Results/SearchFailureInfo.cs#L33) containing the failure message, and here is the [changeset](https://github.com/Anthony-Nolan/Atlas/commit/1bb7d6ccd7f470c88e5d400bcd20002ad0193d43) for more context.
