### ISSUE TITLE
Failed repeat search requests not containing failure info

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1042]
First 4 attempts to process repeat request for `ed546c78-2934-46fa-ab93-0ec6e8775010` failed, most likely due to sleeping matching db. However, the messages published to `repeat-search-matching-results-ready` topic did not contain the search request of the failed search or the failure info:

```
{
  "SearchRequest": null,
  "IsRepeatSearch": true,
  "MatchingAlgorithmServiceVersion": "1.0.0.0",
  "ElapsedTime": "00:00:00",
  "ValidationError": null,
  "FailureInfo": null,
  "SearchRequestId": "ed546c78-2934-46fa-ab93-0ec6e8775010",
  "WasSuccessful": false,
  "RepeatSearchRequestId": "b5e535ee-c4bd-402f-8814-4c6b3ba54a10",
  "BlobStorageContainerName": null,
  "ResultsFileName": null,
  "NumberOfResults": null,
  "MatchingAlgorithmHlaNomenclatureVersion": "3530",
  "ResultsBatched": false,
  "BatchFolderName": null
}

```

Because of missing failure info, the message published to `repeat-search-results-ready` is incorrect by saying the search will /not/ be retried i.e., `WillRetry` is being set to `false`, when it should be `true`.

```
{
  "FailureMessage": "Search failed at stage: Matching Algorithm",
  "FailureInfo": {
    "StageReached": "Matching Algorithm",
    "MatchingAlgorithmFailureInfo": null,
    "WillRetry": false,
    "Summary": "Search failed at stage: Matching Algorithm"
  },
  "MatchingAlgorithmTime": "00:00:00",
  "MatchPredictionTime": "00:00:00",
  "OverallSearchTime": "00:00:00",
  "SearchRequestId": "ed546c78-2934-46fa-ab93-0ec6e8775010",
  "WasSuccessful": false,
  "RepeatSearchRequestId": "b5e535ee-c4bd-402f-8814-4c6b3ba54a10",
  "BlobStorageContainerName": null,
  "ResultsFileName": null,
  "NumberOfResults": null,
  "MatchingAlgorithmHlaNomenclatureVersion": null,
  "ResultsBatched": false,
  "BatchFolderName": null
}
```

**To Reproduce**
1. Check the active matching db is dormant via azure portal.
2. Submit repeat search request via Public API for `ed546c78-2934-46fa-ab93-0ec6e8775010` (or some other request id listed in table `RepeatSearch.CanonicalResultSets`).
3. Go to `repeat-search-matching-results-ready` topic and look for the failure messages.

**Expected behaviour**
Failure messages should have both the search request and failure info.

**Atlas Build & Runtime Info (please complete the following information):**
 - UAT-WMDA-ATLAS
 - Atlas Version: 1.6.0
 - GitHub commit ID of Atlas build: f891ab77

**Comment by zabeen** [comment]
### HLD

Replicate how failure info is set in [MatchingAlgorithm `SearchRunner`](https://github.com/Anthony-Nolan/Atlas/blob/f891ab775af2051e50815ea6ebeaf2c46e037a30/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L122C62-L122C62)

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok
Failure message from `repeat-search-matching-results-ready`:
![image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/3e75099b-d3b8-47fd-8c2e-0bdc0bf55e54)

**Comment by zabeen** [comment]
@DmitriyShcherbina thanks for testing

However, your screenshot does not show the prop: `WillRetry` in the `FailureInfo` object.

@IgorKupreychik could you please investigate?

**Comment by zabeen** [comment]
@DmitriyShcherbina - a fix has been applied for this issue, please could you re-test? Many thanks.

**Comment by DmitriyShcherbina** [comment]
@zabeen Sorry for being not attentive enough to notice issues in previous results
Here are results of re-testing:
![image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/46c20431-600e-4b03-a334-aa111e38935a)
![image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/9e6760cf-e452-41f6-9b98-93d78adb4f9d)

**Comment by zabeen** [comment]
Many thanks @DmitriyShcherbina !
