### ISSUE TITLE
Catch and suppress HMD exception during Repeat Search

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1043]
This is how [HMD exceptions are caught and handled in matching algorithm search runner](https://github.com/Anthony-Nolan/Atlas/blob/f891ab775af2051e50815ea6ebeaf2c46e037a30/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L118).

The same thing needs to be done in the [repeat search runner](https://github.com/Anthony-Nolan/Atlas/blob/f891ab775af2051e50815ea6ebeaf2c46e037a30/Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs#L133).

**Comment by zabeen** [comment]
### Testing

- this is hard to test in a "normal" use case way because if the original search request contained invalid HLA then it would have been rejected, and won't be in the repeat search db to begin with.
- So have to test as follows:
  - run a search with valid HLA, let it complete
  - a few minutes later, run a repeat search for that search request, and change one typing in the request to an invalid value (eg., "bad-hla")
  - check that only one message is published to `repeat-search-results-ready` for that repeat search, with `WasSuccessful` set to `false`, the validation error, and `WillRetry` is set to `false`

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/7538bd3c-2dbb-4d1f-8227-d8fc81276df4)
