### ISSUE TITLE
Store additional donor info in matching database

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1064]
Dependency of matching on donor store leads to the exception described here #1055  

To avoid this issue, three additional fields should be added to the [Donors table](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Data/Models/Entities/Donor.cs) on matching algorithm db:

- `ExternalDonorCode`
- `EthnicityCode`
- `RegistryCode`

These fields should be set via:
- data refresh (via [DonorReader](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.DonorImport/ExternalInterface/DonorReader.cs))
- searchable donor updates (via this [model](https://github.com/Anthony-Nolan/Atlas/blob/a773c7aaf6697d118c9f43d8798cd2da1bc32002/Atlas.DonorImport/ExternalInterface/Models/SearchableDonorInformation.cs#L32C29-L32C29))

### Release Management
- new columns must be seeded before the dependency on donor store during search can be dropped
- a feature flag should be used: `useDonorInfoStoredInMatchingAlgorithmDb`
  - when `false` (default), donor info will be fetched the [existing way](https://github.com/Anthony-Nolan/Atlas/blob/a773c7aaf6697d118c9f43d8798cd2da1bc32002/Atlas.MatchingAlgorithm/Services/Search/SearchService.cs#L88), via call to the donor store db
  - when `true`, donor info stored in the new props will be used instead
  - Trace messages should be used to log which code path was followed so we can be sure the FF is in the correct state.
  - #1066 covers setting up FF infrastructure on Atlas
    - before #1066 is merged, use a `bool` constant as a placeholder for the FF
    - after #1066 is merged, define the new FF as a terraform resource in the [`donor_import` module](https://github.com/Anthony-Nolan/Atlas/tree/master/terraform/core/modules/donor_import) and use IFeatureManager to grab its value (value should be cached as it will be used on every search).
- the easiest way to seed the new columns is via data refresh

Release steps would thus be:
  1. Release changeset (incl. db migration) with the feature flag set to `false` 
  2. Run data refresh job
  3. Set feature flag to `true`
  4. Release changeset to remove donor store dependency (this will be covered by #1067 )

**Comment by zabeen** [comment]
@mmelchers It will take a few weeks to implement, test and release this.

Could you please investigate whether it is a single org who is responsible for the mass deletes and re-creates, followed by 100s of searches that bring the deleted donors back?

If so, could you notify them of the reason for the search failures, and ask them to allow 24 hours for donor updates to propagate before running the searches? At least until the fix has been deployed to live.

**Comment by zabeen** [comment]
@mmelchers understandable, but I was just wondering if it was more than a coincidence that there were so many searches failing for this reason so soon after the mass delete/recreate event.

**Comment by zabeen** [comment]
### Testing Notes

#### Regression test
- Run a search and check that `ExternalDonorCode`, `EthnicityCode` and `RegistryCode` are being populated for each matching donor result.
- To be run:
  - before data refresh, with feature flag set to `true`
  - after data refresh, with feature flag set to `false`

#### Bug fix test
- Pause the [donor management function](https://portal.azure.com/#@ukmarrow.org/resource/subscriptions/6114522f-eea5-44ab-94ab-af37ffffc4d3/resourceGroups/DEV-ATLAS-RESOURCE-GROUP/providers/Microsoft.Web/sites/DEV-ATLAS-MATCHING-DONOR-MANAGEMENT-FUNCTION/appServices)
- Upload a donor import file with a "delete" update
- Run a search that will back the deleted the donor (i.e., patient has same HLA as the deleted donor)
- Outcome: the search should complete successfully, and include the deleted donor as a match

**Comment by zabeen** [comment]
Dev work done, but release and testing blocked by #1066

**Comment by DmitriyShcherbina** [comment]
@zabeen Hi! From my perspective, testing status: Ok

<img width="530" alt="Screenshot at Oct 09 13-46-33" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/3b4960a5-9a2c-425d-8665-f1845536d005">
<img width="208" alt="Screenshot at Oct 09 13-47-42" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/e962f473-5bda-4344-ba46-47fcca1da4a8">
<img width="402" alt="Screenshot at Oct 09 15-25-11" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/ab8f92c2-58ac-4cea-b9f1-fad29d5cbe24">


`e93a6917-455d-4489-a437-46bc542ff9f5` - before `DEV-ATLAS-MATCHING-DONOR-MANAGEMENT-FUNCTION` pause and upload donor import file with 'delete' donors list
<img width="298" alt="Screenshot at Oct 09 15-34-25" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/abfce372-de19-446d-9f06-d8674fdd60cc">


`8dba3c96-2a32-4705-9b4d-3bec1daa5ce9` - after `DEV-ATLAS-MATCHING-DONOR-MANAGEMENT-FUNCTION` restart
<img width="317" alt="Screenshot at Oct 09 15-46-29" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/8d855ac9-b3b7-4e3a-a38a-53e7a29aa882">

**Comment by zabeen** [comment]
### Release to WMDA as of 10th October 2023

- Code changes and data migrations have been released
- Data refresh for v3.54.0 should be taking place this weekend
- Once that completes, the feature flag can be enabled

**Comment by zabeen** [comment]
WMDA release completed, see #1066 for release notes.
