### ISSUE TITLE
Remove call to donor reader during matching

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1067]
~Blocked by #1064~

Once donor info is being saved within the matching db, we can [remove the call to the donor store during search](https://github.com/Anthony-Nolan/Atlas/blob/a773c7aaf6697d118c9f43d8798cd2da1bc32002/Atlas.MatchingAlgorithm/Services/Search/SearchService.cs#L88).

**Important**: This change should not be released until the matching db has been fully seeded with donor info, and the feature flag for #1064 has been set to `true`.

**Comment by zabeen** [comment]
### Testing Notes

Regression tests:
- run 10/10 search
- run repeat search that returns new, updated and deleted donor

**Comment by DmitriyShcherbina** [comment]
@zabeen Regression tests status: Ok


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/0ab2480e-7818-4634-82ac-2f76a64224ac)

Additional tests status:
- DEV-ATLASAPP-CONFIGURATION still exists
- in Feature Manager tab only `useDonorInfoStoredInMatchingAlgorithmDb` flag is displayed and enabled


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/385d6908-c322-4146-8847-6b6c9b7a0bc6)

**Comment by zabeen** [comment]
@daria-sorokina-da  For some reason deletion of the feature flag definition from terraform did **not** lead to it being removed from app configuration.

Is it because we set: 
```  lifecycle {
    ignore_changes = [enabled]
  }```

**Comment by zabeen** [comment]
Terraform logs from the release show that terraform did "destroy" the feature flag definition without error:
> 2023-12-06T14:18:45.8216512Z [0m[0m[1mmodule.matching_algorithm.azurerm_app_configuration_feature.atlas_use_donor_info_stored_in_matching_algorithm_db: Destroying... [id=/subscriptions/6114522f-eea5-44ab-94ab-af37ffffc4d3/resourceGroups/DEV-ATLAS-RESOURCE-GROUP/providers/Microsoft.AppConfiguration/configurationStores/DEV-ATLAS-APP-CONFIGURATION/AppConfigurationFeature/useDonorInfoStoredInMatchingAlgorithmDb/Label/%00]
06T14:18:46.1711102Z [0m[1mmodule.matching_algorithm.azurerm_app_configuration_feature.atlas_use_donor_info_stored_in_matching_algorithm_db: Destruction complete after 0s

However, the actual resource does still exist in Azure. This may be an terraform/ARM bug.

**Comment by zabeen** [comment]
I have manually deleted the FF from app configuration.

@DmitriyShcherbina - please could you redo [the regression tests](https://github.com/Anthony-Nolan/Atlas/issues/1067#issuecomment-1842858580)?

**Comment by DmitriyShcherbina** [comment]
@zabeen Regression tests status: Ok


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/627259ab-7e76-4f1c-9e2e-b25ce2ec4180)

DEV-ATLAS-APP-CONFIGURATION's Feature manager doesn't contain any flags also


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/5fdf67fe-59f0-46cd-80dd-3cc6b46c3ef1)
