### ISSUE TITLE
High amount of inexplicable/unrepresented donors in ATLAS VS Hap-E

### ISSUE THREAD

**Issue by RimkePostel** [Anthony-Nolan/Atlas#1068]
**Describe the bug**
From user reports and some of our own tests it became apparent that ATLAS marks several donors as inexplicable/unrepresented, which are not marked as such by Hap-E.
Moreover, some donors with similar resolution typing as donors that are marked as inexplicable/unrepresented are not marked as such.

**To Reproduce**
This issue has been reported as a discrepancy on share by several users.
See case#: 7, 26, 28, 30

**Expected behaviour**
We would expect ATLAS and Hap-E to behave similarly.

**Screenshots**
See share.

**Inputs/Outputs**
n/a

**Atlas Build & Runtime Info (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by zabeen** [comment]
@RimkePostel Thanks for reporting, I will be looking into more cases this week, will hopefully get an explanation soon.

**Comment by zabeen** [comment]
### Case 7
- Donor inexplicable because the following MACs are not valid according to v3.48.0 of HLA metadata dictionary (HMD):
  - C*04:EEDAF due to allele 04:482
  - C*12:EENFC due to allele 12:330Q
  - DQB1*03:EFSPH due to allele 03:497
  - DQB1*05:EFWZC due to allele 05:299

**Comment by RimkePostel** [comment]
@zabeen Thank you for investigating. So this means we should build in some procedure to handle this gracefully within ATLAS?

**Comment by zabeen** [comment]
Fix has been implemented and is awaiting release to wmda uat for final testing.
