### ISSUE TITLE
XX code typed donors not being returned by Atlas

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1079]
Super user cases: 24, 29B, 32B

**Comment by zabeen** [comment]
### Case 24
- Re-ran the search and the donor was returned as expected.

**Comment by mmelchers** [comment]
@zabeen donor ID's have been provided WMDA Share.

**Comment by RimkePostel** [comment]
@zabeen These issues (for the abovementioned discrepancies) have been resolved!

**Comment by zabeen** [comment]
@RimkePostel wonderful, I will close this issue then.
