### ISSUE TITLE
Run WMDA Validation Set 4

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1095]
Will require some code changes to the manual testing Validation project:
- extend `import subjects` function to allow import of HF set id
- add new function to send the imported donors to the donor store
- new function to run searches using the imported patient data, with ability to set mismatch count and match loci 
- new sb triggered function to download the results to the db
- new function to export set 4 results to csv file

Other tasks:
- use script in `\MiscTestingAndDebuggingResources\ManualTesting\MatchPredictionValidation` to convert hf set files to required schema

**Comment by zabeen** [comment]
### Testing

Regression tests:
1) 10/10 search with match prediction ON
2) Repeat search for new donor (this will implicitly cover donor import)

**Comment by DmitriyShcherbina** [comment]
@zabeen Regression testing status: Ok
![search](https://github.com/Anthony-Nolan/Atlas/assets/107943429/8725c0b5-68b1-4c62-8264-5ed1d65a5ea4)
![repeat](https://github.com/Anthony-Nolan/Atlas/assets/107943429/f14f5f0d-2800-408a-8c6d-1d1404d6dff1)
