### ISSUE TITLE
Create logic apps to report failed WMDA repeat searches

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1102]
Follow same pattern as [existing logic app for failed original searches](https://portal.azure.com/#@ukmarrow.org/resource/subscriptions/3dfd4982-6111-4206-90d5-3ddb84dfa94e/resourceGroups/UAT-WMDA-ATLAS-RESOURCE-GROUP/providers/Microsoft.Logic/workflows/UAT-WMDA-ATLAS-FAILED-SEARCHES/logicApp)

**Comment by jdoherty-nmdp** [comment]
I've created logic LIVE-WMDA-ATLAS-FAILED-REPEAT-SEARCHES and UAT-WMDA-ATLAS-FALIED-REPEATED-SEARCHES logic apps by cloning and tweaking the existing LIVE-WMDA-ATLAS-FAILED-SEARCHES and UAT-WMDA-ATLAS-FAILED-SEARCHES logic apps, respectively. The new apps are currently configured to check the "repeat-search-results-ready" topic and post "!! Failed REPEAT Search Alert !!" notices to the "WMDA-UAT Support" and "WMDA-LIVE Alerts" Teams channels when needed.

**Comment by jdoherty-nmdp** [comment]
The live-wmda-atlas/repeat-search-results-ready topic does not have a "support" subscription, which is what the new logic app uses. Zabeen detected a similar issue with the UAT version last week. I've disabled the new live logic app for now; we can discuss more in stand-up.

**Comment by zabeen** [comment]
Logic app has been enabled on live
