### ISSUE TITLE
scoringresult.totalmatchcount should reflect correct matching category when locus contains null allele

### ISSUE THREAD

**Issue by RimkePostel** [Anthony-Nolan/Atlas#1104]
**Describe the bug**
Search and Match uses the scoringresult.totalmatchcount when importing donor results. Currently, the value for scoringresult.totalmatchcount does not reflect the correct count for donors with Null alleles, leading to limited import of donors that are returned by ATLAS to Search and Match.

**To Reproduce**
For example: see discrepancy 33 on share

**Expected behaviour**
We expect scoringresult.totalmatchcount to reflect to correct matching category so the donors will be returned in Search and Match. The scoringresult.totalmatchcount should be in line with scoringresult.matchcategory and and the matchcategory for loci at the position level to prevent any confusion for our end users.

**Comment by RimkePostel** [comment]
**Suggested workaround** (as discussed earlier with Zabeen)
A suggested possible workaround to circumvent this issue could be to use the matchingresult.totalmatchcount

**Investigation workaround**
After investigation, we concluded that using matchingresult.totalmatchcount instead of scoringresult.totalmatchcount would not provide a solution to the above mentioned issue. 

Switching (back) to matchingresult.totalmatchcount would induce the following issues:
- Using matchingresult.totalmatchcount without changing the information about scoringresult.matchcategory and the matchcategory for loci at the position level, would result in returning of contradictory data. Namely, some of the donors that will be returned as possible 10/10 matches may display a mismatch at loci with Null alleles, which is counter-intuitive for our end users.
- In a 10/10 search, donors with a scoringresults.totalmatchcount = 9 will be returned in the 9/10 matching category instead of the 10/10 matching category, which should not be allowed.
- Using matchingresult.totalmatchcount instead of scoringresult.totalmatchcount will result in returning of donors with serology typing that should not be returned as a possible match, according to our super users. For example, see discrepancy #3 on share.

**Comment by zabeen** [comment]
@RimkePostel I have passed this issue onto the AN algorithm team to get more guidance. This is some of their early feedback regarding whether null allele vs. expressing should be called a mismatch:

> Dr. Sharon Vivers
But at a molecular level it is a mismatch, so when we report it clinically we would identify it as a mismatch but say that because the null isn't expressed then it can be consider a match.
It's about nuance really and I'd hope any Search Coordinator with adequate training would understand the situation.  However, from a usability point of view, we may wish to think about displaying this differently.

I have also asked Nicole Stanley to run search from case 33 and examine the results to see if they are problematic from her perspective as a user.

I will follow up on this with you next week, after the conference.

**Comment by zabeen** [comment]
I have proposed an alternative fix here: #1114

Seeing as AN super-users remain on their original conviction I recommend deferring any decision re: null allele vs. expressing typing grading until after #1114 has been been implemented and tested.

Placing this under blocked until then.

**Comment by zabeen** [comment]
Ticket is now unblocked, awaiting implementation notes from @zabeen

**Comment by zabeen** [comment]
Investigating another fix which is to add a new [match grade](https://github.com/Anthony-Nolan/Atlas/blob/1107f69ff43ad6a645697dea76c35eb243ea56ac/Atlas.Client.Models/Search/Results/Matching/PerLocus/MatchGrade.cs#L9): `ExpressingVsNull` to replace `Mismatch` grade assignment.

**Comment by zabeen** [comment]
### Testing Notes

- I have written automated E2E matching algorithm tests to cover the [new ACs described above](https://github.com/Anthony-Nolan/Atlas/issues/1104#issuecomment-1850669202)
- Need to run regression tests on AN Dev, and then pass ticket to WMDA for UAT

Regression tests for AN dev:
- 10/10 search with scoring and match prediction ON - ensure all requested loci have score values
- repeat search of above request, looking for new donor - ensure new donor is scored

**Comment by DmitriyShcherbina** [comment]
@zabeen Regression testing status: Ok
10/10 Search results
![Screenshot at Dec 19 13-44-15](https://github.com/Anthony-Nolan/Atlas/assets/107943429/6c0262df-05a7-4e53-ad1a-cb6d4fece6f7)

Repeat search result
![Screenshot at Dec 19 14-01-45](https://github.com/Anthony-Nolan/Atlas/assets/107943429/76a57cf4-94a9-4b76-80ba-88a2f5b2dcc9)
