### ISSUE TITLE
"MatchingDonorInfo" contains unupdated donor data in repeat-search-results json file after donor data update before repeat search request

### ISSUE THREAD

**Issue by DmitriyShcherbina** [Anthony-Nolan/Atlas#1108]
**Description**
"MatchingDonorInfo" contains unupdated donor data in repeat-search-results json file after donor data update before repeat search request

**To Reproduce**
1. Run search request
2. Modify "EthnicityCode" for one of donors in search results list (by donor import file upload)
3. Run repeat search request based on search request from step 1, set "SearchCutoffDate" to actual date or date of donor modification
4. Check repeat search results in corresponding directory of <env>atlasstorage

**Actual behaviour**
"MatchingDonorInfo" contains unupdated donor data in repeat-search-results json file after donor data update before repeat search request

**Expected behaviour**
"MatchingDonorInfo" contains updated donor data in repeat-search-results json file after donor data update before repeat search request

**Screenshots**
<img width="308" alt="image" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/16b63f36-e9fa-4cf0-bf95-22c1ea0258c5">
<img width="310" alt="image" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/615bbd46-a10f-4599-b44a-866fddc43312">

**Comment by DmitriyShcherbina** [comment]
@daria-sorokina-da Testing status: Ok

**Comment by RimkePostel** [comment]
Testing in SBX approved
