### ISSUE TITLE
Set PublishedDateTime to UTC now on replayed donor update messages

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1112]
Set PubishedDateTime [here](https://github.com/Anthony-Nolan/Atlas/blob/6ed8fd866dfda1dde1412b560ddb1bdabb8feff2/Atlas.MatchingAlgorithm/Services/DonorManagement/DonorUpdateProcessor.cs#L154C35-L154C35)

Please also add unit test to cover this fix

**Comment by zabeen** [comment]
### Test Notes

1) re-do test explained here: https://github.com/Anthony-Nolan/Atlas/issues/1053#issuecomment-1768760765
2) Check contents of the replayed update message and ensure the published datetime is correct

**Comment by DmitriyShcherbina** [comment]
@zabeen Me and Daria tried to reproduce steps described [here](https://github.com/Anthony-Nolan/Atlas/issues/1053#issuecomment-1778981284) but we only saw that message appeared in `matching-transient-a` and `matching-transient-b` with old "PublishedDateTime" (we re-sent old message from yesterday in audit subscription) and we didn't see how it was moved there and any logs related to that process.

![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/3a0d5508-1c14-4ccf-a5db-82da5f15610c)

Maybe breaking SQL connection isn't enough to reproduce the situation when this algorithm could be tested?

**Comment by zabeen** [comment]
Thanks @DmitriyShcherbina, I will investigate further.

**Comment by zabeen** [comment]
### Testing [2]

#### Method
1. "Break" db connection strings `SqlA` and `SqlB` on [DEV-ATLAS-MATCHING-DONOR-MANAGEMENT-FUNCTION](https://portal.azure.com/#@ukmarrow.org/resource/subscriptions/6114522f-eea5-44ab-94ab-af37ffffc4d3/resourceGroups/DEV-ATLAS-RESOURCE-GROUP/providers/Microsoft.Web/sites/DEV-ATLAS-MATCHING-DONOR-MANAGEMENT-FUNCTION/appServices) by modifying username in the conn string. Save changes,
2. Disable both DLQ listener functions on the same functions app so that any dead-lettered messages will remain on the DLQ.
3. Upload a donor import file with a single new donor. The update message should appear on all subs of `updated-searchable-donors` topic, but will soon disappear from whichever sub represents the "dormant" db. It should remain on the "active db" sub until it dead-letters; this will take about 10-15 mins.
4. After the message dead-letters, make note of the `PublishedDateTime` value in the message contents. 
5. Re-enable the two DLQ listener functions from step 2 and note the time. The dead-lettered message should disappear and be republished to the topic after a minute.
6. Check the contents of the new message, it should have a datetime value similar to the time the DLQ functions were re-enabled.

Cleanup:
- restore db connection strings
- delete the new donor

#### Results
- First `PublishedDateTime`: `2023-11-16T17:02:02.1772852+00:00`
- Second  `PublishedDateTime`: `2023-11-16T17:15:47.9513948+00:00`
