### ISSUE TITLE
Investigate use of Redis with Azure durable functions

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1132]
[Azure cache for Redis](https://azure.microsoft.com/en-gb/products/cache) looks like a good option for implementing a cache for #1131.

Investigate how we can deploy and connect to a Redis cache:
- terraform cache resource
- read and write to it from multiple azure activity functions running in parallel
- should we migrate solution to newer .net to take advantage of increased redis support, or can we make do with .net 6?

**Comment by IgorKupreychik** [comment]
@zabeen I don't see any issues with using Redis for Azure functions with .NET 6 (unless we want to use Redis as a trigger for Azure functions), don't think there will be any issues using it for durable functions.

**Comment by zabeen** [comment]
Thanks @IgorKupreychik 

I plan to discuss the larger issue (#1131) with a solution architect, so will keep this on the backlog for now.
