### ISSUE TITLE
Add file name to alert "Donor Ids file was present but it was empty"

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1142]
> Alert from CheckDonorIdsFromFile
Donor Ids file was present but it was empty.
at Atlas.DonorImport.Services.DonorChecker.LazilyParsingDonorIdFile.ReadLazyDonorIds()+MoveNext() in /home/vsts/work/1/s/Atlas.DonorImport/Services/DonorChecker/DonorIdCheckerFileParser.cs:line 41
at MoreLinq.MoreEnumerable.<>c__DisplayClass23_0`2.<<Batch>g__Batch|2>d.MoveNext()
at Atlas.DonorImport.Services.DonorChecker.DonorIdChecker.CheckDonorIdsFromFile(DonorIdCheckFile file) in /home/vsts/work/1/s/Atlas.DonorImport/Services/DonorChecker/DonorIdChecker.cs:line 57

- Above is the current alert description, but it's not very helpful.
- The name "Donor Ids file was present but it was empty." is fine, but alert `Description` needs to be changed.
- `Description` should list the name of the donor ID checker file that failed.
- Do not need to see the exception message, as we can get that from AI logs if necessary.

Update:
- Alert is raised in response to `EmptyDonorFileException`
- Exception is caught and suppressed so no info is written to A.I., but that is ok because it is a custom exception we only throw when underlying file stream is `null`, so stack trace is not useful
- This is used in three kinds of file import: donor, donor id checker and donor info checker
- In all 3 cases, the stack trace is used as alert description without file name
- Proposed fix should be applied to all three cases

**Comment by zabeen** [comment]
@SergeyEzh 
As discussed over teams, stack trace isn't useful here as we know exactly what causes `EmptyDonorFileException` to be thrown (underlying file stream is `null`).

Further, I see three places in code where `EmptyDonorFileException` is being thrown and caught:
- Donor id checker file import
- Donor info checker file import
- Donor file import

and in each case the stack trace is being written to the `alert` message without file name.

So I am extending this ticket to cover all these cases.

**Comment by SergeyEzh** [comment]
@zabeen, I was doing final testing before commit and now alert message is confusing me. Because it states that file was found but it is empty, though I found that this exception is thrown when I put wrong url to blob to service bus message. When I upload 'real' empty file to blob storage and put correct blob url in service bus it just reads empty file and throws no exception.

**Comment by zabeen** [comment]
@SergeyEzh In real usage, I have only seen this error where a file was dropped into blob storage, which caused an import request message to be published, and then user manually deleted the file from storage before the donor import app imported it. The blob stream generated by the function is `null` and then hits the "empty file" exception (which is really a "missing file").

I am surprised an actual empty file doesn't result in any exception though. Perhaps the check that throws the `EmptyDonorFileException` needs to be extended to `stream is null or empty`?

**Comment by SergeyEzh** [comment]
@zabeen, I would prefer two messages like 'Unable to read file content' in case stream is null and 'The file contains no data' in case no data parsed from stream, rather than checking stream length.

**Comment by zabeen** [comment]
>  I would prefer two messages like 'Unable to read file content' in case stream is null and 'The file contains no data' in case no data parsed from stream, rather than checking stream length.


@SergeyEzh I'll create a new ticket for that work, right now I want to close and deploy this ticket with the existing support enhancement.

**Comment by zabeen** [comment]
### Testing Notes

Feature test:
- First pause donor import (either stop the functions app or disable the `donor-import-file-uploads.donor-import` service bus sub)
- Upload a valid donor import file.
- After a new message has been published to `donor-import-file-uploads` for that file, manually delete the donor import file from the blob storage container.
- Now re-enable donor import (i.e., undo first step)
- Outcomes:
  - Alert should be published saying "file was present but it was empty" and name of the affected file.

Repeat same test with:
- donor id checker file
- donor info checker file

Regression tests:
- run donor import of new donor
- run donor id check
- run donor info check

**Comment by DmitriyShcherbina** [comment]
@zabeen Feature testing status: Ok
<img width="513" alt="donor import alert" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/233cd992-7519-4916-9049-0993822664ed">
<img width="610" alt="donor ids" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/af997adf-761c-4be6-927c-466cdd3fb122">
<img width="569" alt="Screenshot at Jan 09 14-41-26" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/68f90e8d-ee17-402a-ad33-a3325eeb7d6a">

Regression testing status: Ok
<img width="495" alt="donor-import-success" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/0776a299-5459-470e-9961-a50dd0fc4328">
<img width="494" alt="donor-id-checker-success" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/dad9d0a9-8050-4963-a6f6-d6fd4823bcd2">
<img width="493" alt="donor_info_success" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/a4b29307-b66f-4b65-8540-42afb502ac7e">
