### ISSUE TITLE
Debug endpoint to retrieve random donors for test generation

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1144]

**Comment by zabeen** [comment]
@DmitriyShcherbina I added a new debug endpoint to allow QA to retrieve donor data for use in testing.

You'll find it in [donor import function](https://portal.azure.com/#@ukmarrow.org/resource/subscriptions/6114522f-eea5-44ab-94ab-af37ffffc4d3/resourceGroups/DEV-ATLAS-RESOURCE-GROUP/providers/Microsoft.Web/sites/DEV-ATLAS-DONOR-IMPORT-FUNCTION/appServices): `GetRandomDonors` - it'll be visible once the changes have been released to dev in a few mins.

Load [swagger UI](https://portal.azure.com/#view/WebsitesExtension/FunctionMenuBlade/~/functionOverview/resourceId/%2Fsubscriptions%2F6114522f-eea5-44ab-94ab-af37ffffc4d3%2FresourceGroups%2FDEV-ATLAS-RESOURCE-GROUP%2Fproviders%2FMicrosoft.Web%2Fsites%2FDEV-ATLAS-DONOR-IMPORT-FUNCTION%2Ffunctions%2FSwaggerUi) to see the optional parameters of `donorCode` and `registryCode` if you only want to retrieve a particular kind of donor.

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok
Results look good, thanks!



![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/877f4380-868c-41a4-b8d2-c23a6deee46e)

![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/4baa6430-078a-4fde-b437-5799586dd47a)
