### ISSUE TITLE
 SubmitDataRefreshRequest should not throw exception when scheduled and no data refresh required

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1149]
- [`SubmitDataRefreshRequest` is a timer function](https://github.com/Anthony-Nolan/Atlas/blob/2cc92f09ba3ad60616a6636b4fc07b9bb3125c06/Atlas.MatchingAlgorithm.Functions/Functions/DataRefreshFunctions.cs#L62) on `Atlas.MatchingAlgorithm.Functions` that submits a non-forced data refresh request according to schedule
- If HMD does not need to be recreated (and because the request is non-forced), currently an [exception is thrown](https://github.com/Anthony-Nolan/Atlas/blob/2cc92f09ba3ad60616a6636b4fc07b9bb3125c06/Atlas.MatchingAlgorithm/Services/DataRefresh/DataRefreshRequester.cs#L69C45-L69C45)
- The exception is registered within AI as a failed request which we are monitoring in Live, so it means support is wasting a few mins looking into the Failures when it is not needed.
- As this is an acceptable scenario - i.e., we expect most scheduled requests to not lead to data refresh - an exception should not be thrown in the automated case.

Solution:
- if `wasManuallyRequested` is `false`, then log the error message as a Warning Trace instead and early return `new DataRefreshResponse {WasRefreshRun = false};`
- else (if a manual request) then throw the exception, as currently happens.

**Comment by zabeen** [comment]
### Testing Notes

#### Feature testing
On AN Dev, HMD is already on latest version and so any non-forced requests should not lead to data refresh running.

Test of the Scheduled job: 
  - Update [matching algorithm app settings](https://portal.azure.com/#@ukmarrow.org/resource/subscriptions/6114522f-eea5-44ab-94ab-af37ffffc4d3/resourceGroups/DEV-ATLAS-RESOURCE-GROUP/providers/Microsoft.Web/sites/DEV-ATLAS-MATCHING-ALGORITHM-FUNCTIONS/configuration):
    - `DataRefresh:AutoRunDataRefresh` to `true`
    - `DataRefresh:CronTab` to suitable value to prompt the function `SubmitDataRefreshRequest` to run during the test period
  - After the schedule run, check results:
    - it should have completed successfully
    - AI logs should show a trace warning message: "Active HLA metadata dictionary is already on the latest version of the WMDA HLA nomenclature and refresh was not run in 'Forced' mode."
  - **Clean up**: reset the app settings to original values

Regression Test of Manually triggered job:
- Send http request to [SubmitDataRefreshRequestManual](https://portal.azure.com/#view/WebsitesExtension/FunctionMenuBlade/~/functionOverview/resourceId/%2Fsubscriptions%2F6114522f-eea5-44ab-94ab-af37ffffc4d3%2FresourceGroups%2FDEV-ATLAS-RESOURCE-GROUP%2Fproviders%2FMicrosoft.Web%2Fsites%2FDEV-ATLAS-MATCHING-ALGORITHM-FUNCTIONS%2Ffunctions%2FSubmitDataRefreshRequestManual) with request body `{"forceDataRefresh": false}`
- Results:
  - Request should return `500` error
  - Exception should be logged to AI: "Active HLA metadata dictionary is already on the latest version of the WMDA HLA nomenclature and refresh was not run in 'Forced' mode."

**Comment by DmitriyShcherbina** [comment]
@zabeen Feature testing status: Ok
<img width="716" alt="Screenshot at Dec 13 17-04-28" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/f5ae08da-d6fc-4b9f-8943-9b3de734fe0c">

Regression testing: `SubmitDataRefreshRequestManual` with `forceDataRefresh: false` returned `400` error but not `500`
<img width="448" alt="Screenshot at Dec 13 17-07-57" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/f98fc56e-380d-433a-8019-9c02a66a882c">

**Comment by zabeen** [comment]
@DmitriyShcherbina 
> Regression testing: SubmitDataRefreshRequestManual with forceDataRefresh: false returned 400 error but not 500

Ah, that seems ok, as it's `BadRequest` error. As long as it returns a sensible error code, I consider it a pass.
