### ISSUE TITLE
Configure Atlas to be able to reject Full mode donor import files

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1155]
Work prompted by live support issue for WMDA-ATLAS.

Donors were missing from search because donor import files had been uploaded in `Full` mode instead of `Diff` mode, which meant no internal updates had been published for these donors, and they were not visible to matching algorithm.

Further, the error was not caught by the donor-id-checker feature as it only checks the donor store db, not the active matching algorithm db.

One mitigation for this exception path is to allow Atlas to reject `Full` mode files, as they are only intended for use when setting up a new install of Atlas.

### HLD
- add a new bool app setting to Donor Import functions app: `allowFullModeImport`
- it should default to `false` 
- Add check to [DonorFileImporter](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.DonorImport/Services/DonorFileImporter.cs) - if file is in full mode and `allowFullModeImport` is `false`, then mark the entire import as failed, and raise an alert.
- terraform new setting, and allow it to be set by release var

**Comment by zabeen** [comment]
### Testing Notes

- Check [donor import functions config](https://portal.azure.com/#@ukmarrow.org/resource/subscriptions/6114522f-eea5-44ab-94ab-af37ffffc4d3/resourceGroups/DEV-ATLAS-RESOURCE-GROUP/providers/Microsoft.Web/sites/DEV-ATLAS-DONOR-IMPORT-FUNCTION/configuration): `DonorImport:AllowFullModeImport` should be `false`
- Upload a valid donor import file in `Full` mode:
  - import result message should says `wasSuccess` is `false`
  - alert message says file was not imported as full mode import not allowed
- Upload a valid donor file in `Diff` mode:
  - import result message should says `wasSuccess` is `true`
  - no alert message
- Manually set `DonorImport:AllowFullModeImport` to `true`
- Upload a valid donor import file in `Full` mode:
  - import result message should says `wasSuccess` is `true`
  - no alert message
- Again, upload a valid donor file in `Diff` mode:
  - import result message should says `wasSuccess` is `true`
  - no alert message
- Clean-up - make sure to reset `DonorImport:AllowFullModeImport` to `false`

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok
`DonorImport:AllowFullModeImport`=`false`
<img width="437" alt="Screenshot at Jan 26 17-24-10" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/eefd22fd-c3f0-41e5-ad98-8816ac97e0e0">
<img width="422" alt="Diff success" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/755319ed-a0a5-4e0e-9579-f9ac9e464f3c">

`DonorImport:AllowFullModeImport`=`true`
<img width="375" alt="Full success" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/c5af65f4-3fc3-4ddf-990f-e05df4207bb3">
<img width="372" alt="Diff Success with full-true" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/69d1233e-3b79-4211-bc3b-605f541e026e">

**Comment by DmitriyShcherbina** [comment]
@zabeen Regarding extendng E2E test-cases with this scenarios, maybe it makes sense to create separate ticket for it, in order not to delay this tested ticked in AN Dev Testing status?

**Comment by zabeen** [comment]
@DmitriyShcherbina makes sense, I just added a comment to end of the existing E2E tests ticket we've had open for a while
