### ISSUE TITLE
Import message should not dead-letter after DuplicateDonorFileImportException

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1186]
Scenario:
- Message for the same donor import file was published 3 times to `donor-import-file-uploads`
- The first message was processed successfully and a single message was published to `donor-import-results`, as expected.
- The second and third messages lead to `DuplicateDonorFileImportException`s being raised, as expected.
- However, the "duplicate" messages were then replayed leading to multiple exceptions of the same type being logged.
- Two messages were published to `donor-import-results` with `wasSuccessful` set to `false`, and `FailureReason` set to `RequestDeadlettered`.

Expectation:
- The second and third message should lead to `DuplicateDonorFileImportException` as happens now.
- But this exception should lead to:
  - the message being immediately dequeued
  - a failure message being published to `donor-import-results` with:
    -  `wasSuccessful` set to `false`
    - `FailureReason` set to `ErrorDuringImport`
    - `FailureReasonDescription` set to inner exception message of the `DuplicateDonorFileImportException`

**Comment by zabeen** [comment]
Failed integration test needs to be fixed. Moving back to In Progress.

**Comment by SergeyEzh** [comment]
@zabeen, during fixing failed test I realized that probably fixed bug incorrectly. In case of DuplicateDonorFileImportException, do we need to call `UpdateDonorImportRecord` ?

**Comment by zabeen** [comment]
>  In case of DuplicateDonorFileImportException, do we need to call UpdateDonorImportRecord ?

@SergeyEzh No. [Looking at the code](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.DonorImport/Services/DonorImportFileHistoryService.cs#L64), Duplicate exception only gets thrown when trying to register a second attempt to import a file which is already in the process of being imported. The exception gets thrown and no second record is created. So there will only be one record row in the table, that belongs to the first valid attempt at import. This should not be updated.

**Comment by zabeen** [comment]
### Testing

- Regression: all Atlas E2E tests (incl. donor import) are passing on DEV
- Fix: TBC
