### ISSUE TITLE
Matching - Move RegistryCode filtering to earlier stage

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1271]
Registry filtering step in `SearchService`: `var resultsFilteredByDonorDetails = donorDetailsResultFilterer.FilterResultsByDonorData` could be moved to earlier in matching

e.g., where all the other donor info filtering is done:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm/Services/Search/Matching/MatchingService.cs#L104

Or to the database layer itself, now that `RegistryCode` is being stored in the matching db `donors` table.

**Comment by SergeyEzh** [comment]
@zabeen , https://github.com/Anthony-Nolan/Atlas/blob/4b91dea08eb072d585a473712864fdfea8da158b/Atlas.MatchingAlgorithm/Services/Search/Matching/DonorMatchingService.cs#L126 -- I'd propose eliminate this, `Dictionary.ContainsKey` works as fast as `HashSet.Contains` do. But taking into consideration batch size, it worth save 5Mb RAM and some CPU time spent on copying data just for fitting to type `HashSet<T>`
