### ISSUE TITLE
Allow MPA and matching components to run at different HLA nomenclature versions

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#636]
### Discussed in https://github.com/Anthony-Nolan/Atlas/discussions/635

<div type='discussions-op-text'>

<sup>Originally posted by **zabeen** July 21, 2021</sup>
Q: does the HLA nomenclature version of a haplotype frequency dataset have to be the same as that used by the matching algorithm component?</div>

**Comment by benbelow** [comment]
@zabeen and I have discussed the approach to this and agreed an approach: 

* Instead of the nomenclature version used to generate the HF set, we should use the nomenclature used in *matching* to expand donors to g groups
* This is already provided as part of the output of matching - so it shouldn't be too much effort to pipe this in instead.

**Comment by zabeen** [comment]
**Investigation of why exceptions were being thrown when HF set is on HLA version v3430 and matching algorithm is on v3450:**
[investigation.pdf](https://github.com/Anthony-Nolan/Atlas/files/6949339/investigation.pdf)

**Solution**

After discussing several approaches, we settled on the following:
- Matching algorithm: continue to use latest HLA version when expanding patient and donor typings.
- Match prediction: 
  - Use the HLA version of the HF set when converting subject typings to small g/large G, prior to haplotype lookup.
  - This will stop exceptions being thrown when haplotypes are converted to P groups in the haplotype matching step.
  - But it will also lead to metadata dictionary lookup exceptions if the subject typing belongs to a later HLA version, e.g., a newly discovered allele, or a known allele that been renamed due to a related allele being discovered (e.g., 01:01 -> 01:01:01).
  - For now, exceptions during subject typing conversion to small/large G will be caught and suppressed, and logged to AI.
  - This will allow search to complete without error, but will lead to more cases where match predictions cannot be calculated as the subject will be called "unrepresented"; Issue #637 has been raised to address this problem.

**Testing**
[Testing.pdf](https://github.com/Anthony-Nolan/Atlas/files/6949357/Testing.pdf)


**Conclusion**
Testing passed, change merged to `master`, and Atlas version incremented to `stable/1.1.0`.
