### ISSUE TITLE
Subject being labeled as unrepresented due to changes in allele names between nomenclature versions

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#637]
See #636 for background.

**Problem**
The solution for #636 introduces a new problem: if a subject's typing contains an allele that is not valid according to the HLA version of the referenced HF set, then the match probability service will not be able to convert the phenotype to small g/large G, which will prevent haplotype lookup; the subject will then be labelled "unrepresented".

A HLA typing could fail to be converted either because:
1. it is a brand new allele, first reported in a HLA version later than that of the HF set.
  - E.g., if HF set is `v3430`, then the allele `A*01:378` would not be found, as it was introduced in `v3450`.
  - This would also apply if the typing was a MAC that expands to a new allele, or a G/P group typing introduced in a later version.
2. it is a previously identified allele that has been renamed for some reason.
  - E.g., it now has an `N` or `L` suffix.
  - E.g.,  A related allele has been found, such as `A*02:921`-> `A*02:921:01`.

In either scenario, the newly named allele may map to a small/large G group that is present within the referenced HF set, and therefore it would be a mistake to call the subject "unrepresented" by default.

**Solution**
Having discussed several approaches, we have settled on the following solution:

1. HLA meta dictionary (HMD) should be automatically "refreshed" to the latest HLA version every time a release becomes available (typically, once every 3 months).
  - this would mean de-coupling this process from the larger data refresh job, which currently involves both recreating the HMD and re-processing all donor typings within the matching algorithm.
2. A new API endpoint should be added to the HMD to allow HLA lookups according to the latest HLA version.
  - At the moment, the HMD is built to a named version during runtime; there is no option or concept of "latest known version".
3. [In the event that a HLA typing fails conversion to small/large G](https://github.com/Anthony-Nolan/Atlas/blob/093f27f56ce3f443dbe721c3a46c640549e4ef5b/Atlas.MatchPrediction/Services/CompressedPhenotypeExpansion/CompressedPhenotypeConverter.cs#L66), the service should use the new endpoint to try to repeat the conversion, with the aim of attaining a small/large G value that is valid according to the HLA version of the HF set.
  - if the typing is a single allele, lookup the older names of said allele, and re-attempt small/large G group conversion.
  - if the typing is an allele string (MAC or G/P group), expand the string and lookup older names of alleles in the string (or just the allele that initially failed conversion), and re-attempt small/large G group conversion.

**Comment by zabeen** [comment]
> if the typing is a single allele, lookup the older names of said allele, and re-attempt small/large G group conversion.
if the typing is an allele string (MAC or G/P group), expand the string and lookup older names of alleles in the string (or just the allele that initially failed conversion), and re-attempt small/large G group conversion.

Having thought about it again, I am not sure this is the solution, because a brand new allele will have no "older name" with which to perform a g group lookup.

Example is [case 7 from WMDA super user testing](https://github.com/Anthony-Nolan/Atlas/issues/1068#issuecomment-1734180063). MAC C*04:EEDAF contains the allele C*04:482 which was released in v3.49.0. It is not present in v.3.48.0 of the HMD, the version that HF sets are currently encoded in, which caused a HMD lookup exception and the donor being labelled "unrepresented".

In the latest version of HMD (currently, v3.53.0),  C*04:EEDAF maps to only one small g group: 04:01g. This small g group is valid according to v3.48.0 of the HMD, and is found in many haplotypes.

So the solution could be:
1) First try HMD lookup at the HLA version that the HF set is encoded in (current implementation)
2) If it fails, re-attempt the lookup using the active version of the HMD
  - this shouldn't require the decoupling work described in the ticket
  - instead, `CompressedPhenotypeConverter` can simply build a second copy of the HMD using [ActiveHlaNomenclatureVersionAccessor](https://github.com/Anthony-Nolan/Atlas/blob/38e6a6298858269aa1159c39b40dd0fe33bee882/Atlas.MatchingAlgorithm/Services/ConfigurationProviders/ActiveHlaNomenclatureVersionAccessor.cs#L26) - see this [example](https://github.com/Anthony-Nolan/Atlas/blob/38e6a6298858269aa1159c39b40dd0fe33bee882/Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs#L32), and call it "active HMD"
  - The g group value returned by "active HMD" does not have to be verified against the "HF set HMD", because we know that an "invalid" value won't be listed in the HF set. At worst, the typing may still end up as unrepresented.

### Testing
- This change should only impact those individuals that have been deemed unrepresented due to HMD lookup failures, as the existing approach will be attempted first. So all automated tests should still pass.
- New automated tests should be added as appropriate.

**Comment by zabeen** [comment]
> if the typing is a single allele, lookup the older names of said allele, and re-attempt small/large G group conversion.
if the typing is an allele string (MAC or G/P group), expand the string and lookup older names of alleles in the string (or just the allele that initially failed conversion), and re-attempt small/large G group conversion.

Having thought about it again, I am not sure this is the solution, because a brand new allele will have no "older name" with which to perform a g group lookup.

Example is [case 7 from WMDA super user testing](https://github.com/Anthony-Nolan/Atlas/issues/1068#issuecomment-1734180063). MAC C* 04:EEDAF contains the allele C* 04:482 which was released in v3.49.0. It is not present in v.3.48.0 of the HMD, the version that HF sets are currently encoded in, which caused a HMD lookup exception and the donor being labelled "unrepresented".

In the latest version of HMD (currently, v3.53.0),  C* 04:EEDAF maps to only one small g group: 04:01g. This small g group is valid according to v3.48.0 of the HMD, and is found in many haplotypes.

So the solution could be:
1) First try HMD lookup at the HLA version that the HF set is encoded in (current implementation)
2) If it fails, re-attempt the lookup using the active version of the HMD
  - this shouldn't require the decoupling work described in the ticket
  - instead, `CompressedPhenotypeConverter` can simply build a second copy of the HMD using [ActiveHlaNomenclatureVersionAccessor](https://github.com/Anthony-Nolan/Atlas/blob/38e6a6298858269aa1159c39b40dd0fe33bee882/Atlas.MatchingAlgorithm/Services/ConfigurationProviders/ActiveHlaNomenclatureVersionAccessor.cs#L26) - see this [example](https://github.com/Anthony-Nolan/Atlas/blob/38e6a6298858269aa1159c39b40dd0fe33bee882/Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs#L32), and call it "active HMD"
  - The g group value returned by "active HMD" does not have to be verified against the "HF set HMD", because we know that an "invalid" value won't be listed in the HF set during the [haplotype filtering step](https://github.com/Anthony-Nolan/Atlas/blob/38e6a6298858269aa1159c39b40dd0fe33bee882/Atlas.MatchPrediction/Services/CompressedPhenotypeExpansion/CompressedPhenotypeExpander.cs#L128C74-L128C74). At worst, the typing may still end up as unrepresented.

### Testing
- This change should only impact those individuals that have been deemed unrepresented due to HMD lookup failures, as the existing approach will be attempted first. So all automated tests should still pass.
- New automated tests should be added as appropriate.

**Comment by zabeen** [comment]
### Dev Testing Notes

- Regression test: run 10/10 search with match prediction on, and check it completes successfully and match prediction object is populated in results file.


- Feature test:
  - create a donor that has high res typings at 5 loci, where at least one typing is an allele that is not valid in v3.48.0
  - after import, run a 10/10 search using the same HLA
  - the search should complete successfully, and the results should contain the new donor, both patient and donor should be represented, and probability of 0mm should be 100.

**Comment by DmitriyShcherbina** [comment]
@zabeen Regression test result: Ok


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/4c8e1e14-b0b0-45c7-95bb-34eb56074ac2)

**Comment by zabeen** [comment]
### Feature Testing on Dev
- created a donor that has high res typings at 5 loci
- after import, ran a 10/10 search using the same HLA, but with `DRB1*03:EEPXR` (that contains `03:199`) in place of `03:01`
- the search completed successfully
- the results contained the new donor
- both patient and donor were represented
- probability of 0mm was 100%
