### ISSUE TITLE
DPB1 TCEdigest directionality of non-permissive mismatch is not indicated

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#645]
For the DPB1 match grade there are values that indicate a permissive, non-permissive or unknown type mismatch. However for DPB1 it is very important to know the directionality of the DPB1 non-permissive mismatch. 

It is a must-have.

Could you add that to ATLAS?

**Comment by benbelow** [comment]
see: https://github.com/Anthony-Nolan/Atlas/blob/d29c867a881e8f1a3ae4b3702198874efc4e0ad7/Atlas.MatchingAlgorithm/Models/Dpb1TceGroupMatchType.cs#L15

**Comment by WMDAJesse** [comment]
Ready for testing

**Comment by benbelow** [comment]
Testing: 
![image](https://user-images.githubusercontent.com/8653532/159491173-3fbe48f8-d108-4cce-af74-fb1dfdb903cc.png)
Confirmed that mismatch directionality is returned in Atlas search results. 

Also confirmed that "NotApplicable" is used for non-mismatches at DPB1, and that null is used for non-DPB1 loci.
