### ISSUE TITLE
Publish public nuget package to expose client models from Atlas 

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#649]
These models are already isolated in a Client.Models C# project. 

We should add a nuget release to our CI release pipeline, including an appropriate versioning strategy.

We should ensure documentation comments are included in this package - this should make things a bit easier for consumers to integrate the product.

**Comment by zabeen** [comment]
The packages can now be released to either public or private NuGet repo. Raising a new ticket to complete documentation on the models within the package, as it's not consistent across the project.
