### ISSUE TITLE
Return HF set information with search results 

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#650]
- Not just internal (PK) id for debugging purposes, but also metadata - nomenclature, ethnicity, registry, and population id

**Comment by benbelow** [comment]
N.B. There will be one HF set for patient, and a (potentially) independent HF set for each returned donor.

**Comment by WMDAJesse** [comment]
Add all of the above fields to MatchProbabilityResponse and add mapping

**Comment by WMDAJesse** [comment]
Ready for testing

**Comment by benbelow** [comment]
@mmelchers and I have noticed a bug with this implementation - if either the patient or donor HLA is considered unrepresented in the HF set chosen, there is an early return with no probability data. We would still like the selected HF set details to be returned in this case, but they were not added to this early return.

**Comment by benbelow** [comment]
Testing: 
![image](https://user-images.githubusercontent.com/8653532/159490751-047f2105-db62-4cbc-ae5f-90786c89720c.png)
Confirmed that all necessary data is returned as part of the final result set. 

✔️
