### ISSUE TITLE
Matching Algorithm Results - Indiciate *which* allele pair is which grade

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#651]
Some discussion with @mmelchers needed to solidify exact requirements here. 

We currently have 2x match grades per locus, and we know whether this was a cross/direct match - we *should* be able to fairly simply piece these together to indicate which position is which, but more investigation is required.

**Comment by WMDAJesse** [comment]
Does grade 1 equal to donor allele 1 or patient allele 1 or arbitrary. We want it to be donor allele 1.

**Comment by zabeen** [comment]
added this ticket as prompt to investigate how scoring match grades are being assigned currently, as it impacts the solution for #996 which has assumed that scoring grades were /not/ oriented arbitrarily!

**Comment by zabeen** [comment]
Having gone through the code, positional scores were not being assigned arbitrarily, rather they are assigned in relation to patient position.

However, it does make more sense for it to be orientated wrt donor position. I am closing this ticket and raising a new one to cover the donor orientation change.
