### ISSUE TITLE
Terraform used is out of date

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#679]
As a product owner I expect that the tools and software is up-to-date so that I can prevent issues from occurring. This includes the use of Terraform. Since it is interacting with Azure and Azure is constantly updating and changing, I want to stay up to date. 

The version used during deployment is version 0.12.24 (released March 19, 2020) 

Latest version at time of writing: 1.1.5  (released February 02, 2022)

**Comment by zabeen** [comment]
This has been resolved as of [this commit](https://github.com/Anthony-Nolan/Atlas/commit/94d31fc61aa87e7223d7594796c557626bebffe1).
