### ISSUE TITLE
Use up-to-date .net version

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#681]
Currently all ATLAS "projects" are running on dotnet core 3.1 

`<TargetFramework>netcoreapp3.1</TargetFramework>`

As can been seen below and in the provided link this version is only supported until the end of this year. 

![image](https://user-images.githubusercontent.com/44259052/152991784-440f9efc-2781-43cb-8247-d7825a99aef2.png)

See https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Therefore we should update the version used to the latest stable version. This would be .net 6 at the moment of writing.

**Comment by benbelow** [comment]
Quick update on this - on the whole this migration is straightforward, but unfortunately we're having some issues with integration tests. 

Locally all tests still work ok, but when running in AN's CI server we're getting consistent SQL related errors in just the matching algorithm's integration test suite. 

These issues are not seen in any other integration test suites in the solution, despite them also using cloud SQL databases to run against. 

This is the only blocker to merging the framework update and running some smoke tests, but it's quite an unknown, and has a slow rate of testing (as we can't repro it locally, any fixes are only ever speculative, but take ~10 min to test in the cloud CI server) so I could see it taking quite a while to resolve
