### ISSUE TITLE
Scaling of matching database does not seem to be configurable from Terraform

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#683]
As a product owner I expect that I can set the scaling parameters of ATLAS from pipeline variables so that I can optimally scale the environment for the need

This seems to work for 
TF_VAR_DATABASE_SHARED_EDITION
TF_VAR_DATABASE_SHARED_MAX_SIZE
TF_VAR_DATABASE_SHARED_SKU_SIZE
TF_VAR_ELASTIC_SERVICE_PLAN_SKU_SIZE
TF_VAR_MATCHING_MAX_CONCURRENT_PROCESSES_PER_INSTANCE
TF_VAR_MATCHING_MAX_SCALE_OUT

but not for TF_VAR_MATCHING_DATA_REFRESH_DB_SIZE_ACTIVE  which I assume sets the DB compute size for the active matching database. The standby database compute size is also not settable.

**Comment by benbelow** [comment]
`but not for TF_VAR_MATCHING_DATA_REFRESH_DB_SIZE_ACTIVE which I assume sets the DB compute size for the active matching database. The standby database compute size is also not settable.`

That variable is used to scale the active matching database, yes. 

This has worked consistently throughout AN's testing, please could you be more specific by what you mean when you say this variable is "not working"?

**Comment by mmelchers** [comment]
If I set it through the set_variables file or directly using pipeline variables from a variable group, it just does not get applied. No error message or anything

**Comment by benbelow** [comment]
What values are you using? I'm aware from my time with this in development that some Azure Terraform parameters, particularly around database scale and memory size, are really awkwardly specific - they require exactly the supported values by microsoft, and if they don't match an expected value - as you say, they're silently ignored and the default used 😭

**Comment by benbelow** [comment]
@mmelchers as this has consistently worked in the AN test environment (with the above caveat that Azure is silently very strict about allowed values), I'm going to close this issue. If you need help finding allowed values to get this to work for your environment, could you either check in on Teams, or raise a new discussion in this repo instead of an issue? Cheers!
