### ISSUE TITLE
ATLAS needs very high level of resources to have any kind of performance

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#686]
In order to run searches with our donor dataset and having any possibility of having them finish, we need very high database specs leading to very high level of costs. Some preliminary work with ATLAS suggests we would be spending about 3 thousand euros a month just to run the algorithm. This is very high compared to other matching algorithms HAP-E and Optimas.

**Comment by zabeen** [comment]
Closing this, as it is covered by both #957 and #906
