### ISSUE TITLE
Some diplotypes are double counted during match prediction calculation

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#687]
After some digging into the code for performance investigations, I believe that the code as written may be double counting some frequencies, which could skew the final probabilities slightly in a direction determined by the double counted frequencies.

In broad strokes, the match prediction algorithm: 

* (1) Expanded donor/patient genotypes to all possible genotypes
* (2) Calculates likelihoods for each of these expanded genotypes
* (3) For all combinations of patient/donor genotypes, calculates match counts
* (4) Combines the likelihoods from (2) and the match counts from (3) to come up with final probabilities. 

The potential issue lies in step (2) - as part of calculating likelihoods, each genotype is treated as if its phase is unknown, and so is expanded (by swapping positions of alleles in the genotype to build all possible haplotypes that could create such a genotype.). This is expected to create 2^n combinations for a fully heterozygous genotype, and fewer options with homozygous loci. 

This is all reasonable, assuming that the genotypes have been generated with no knowledge of phase (as was the case in the early development of this algorithm). **However** - this is not actually the case in step (1). In fact, the "genotypes" generated in the expansion step (1) are generated by combining known haplotypes from the selected frequency set - and combining haplotypes actually generates _**diplotypes**_ (known phase) rather than _**genotypes**_ (unknown phase).

I _believe_ this means that in step (2), any **genotypes** that are represented multiple times in the **diplotypes** generated in step (1) will be double counted when calculating the likelihood of that diplotype.

I'm not 100% confident in this theory, and would like to get a second opinion / look over it with a fresh pair of eyes - but I'll commit a change that addresses this by working out likelihoods in step (2) treating the expanded HLA data as **diplotypes** - which has an added beneficial side effect of improving performance, as it removes a lot of expansion work for these "ambiguous by phase only" genotypes.

**Comment by benbelow** [comment]
This is difficult to test directly. As part of the WMDA-MVP stable version tag release, we will need to re-run MPA verification, to cover testing both for this and for #682. I'll leave this issue open until the verification framework has been run and confirmed that the MPA is still giving reasonable results.

**Comment by zabeen** [comment]
Did not re-run verification, but Atlas did pass validation against the wmda consensus validation dataset [link to writeup](https://drive.google.com/drive/folders/1vI1pgqwiqZCFaJlAfzq41v3loWH6SqP7).
