### ISSUE TITLE
Allow bulk scoring of donors against a single patient genotype directly from the matching functions app

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#710]
Currently an HTTP function entry point exists to score a single patient/donor pair.

For a consumer with a lot of donors to score, this won't be good enough, performance wise - we need the ability to score a batch of donors together. 

For the first iteration of this feature, the entry point will be directly in the matching algorithm functions app, rather than via the public api functions app. If consumers with very high scoring load are worried about this affecting the performance of search requests, then a new issue should be raised to re-architect this feature, likely to use an internal queue like search requests, to allow asynchronous and throttled scoring requests.

**Comment by zabeen** [comment]
Work seems to be done, so closing the ticket.
