### ISSUE TITLE
ATLAS resources should not be reachable from internet. Even when there is password authentication

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#711]
The data contained within ATLAS databases is sensitive. No ATLAS related resources should therefore be accessible from the internet. Even when there is password authentication in place. I suggest making use of VNET integration and Private endpoints using a configurable VNET wherever possible. That was we can precisely control the traffic flowing into and out of the ATLAS environment(s).

**Comment by zabeen** [comment]
@luken-an has said this is no longer an issue now Atlas is hosted on AN's tenant
