### ISSUE TITLE
Add summary of expected settings to tune performance per instance

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#713]
There are a lot of terraform variables available to a maintainer of Atlas to tweak for their instance, of which some are extremely vital to get right for your data size and expected load of an Atlas installation, and others will rarely need to be changed.

As part of the Installation readme, we'd like a succinct summary that tells an installer of Atlas:

 * what TF variables are available to tune performance of an installation
 * what effect they have on performance
 * which functions app / app setting the TF var is converted into in Azure

**Comment by benbelow** [comment]
Pending review from @mmelchers as well as the usual AN review process, as he's the requester and target audience for this document.

**Comment by zabeen** [comment]
Closing as we have completed install of Atlas on DEV and PROD in WMDA.
