### ISSUE TITLE
Make per-locus mismatch probabilities configurable

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#726]
According to data gathered during development of the Match prediction algorithm in 2020,  p(1mm) and P(2mm) per locus added ~30% to search times.

If this data is not used in practice by a consumer, we could look into adding configuration to the search request to allow the consumer to decide whether this data should be included - then consumers that do not use these values will be able to shave a bit of time off their search requests.

**Comment by benbelow** [comment]
@mmelchers I recall you saying this would be useful information, so I won't propose we do this for WMDA's installation - but if you find that you're not planning to use the per-locus mismatch probabilities, it's worth having this piece of work on the radar as a potential saving!

**Comment by benbelow** [comment]
Although it's also worth noting that the 30% figure came from quite early in the MPA development - we'd want to re-test this to see how much time is actually being spent generating these numbers. My *suspicion* is that we wouldn't save nearly that amount in the current iteration of the algorithm

**Comment by zabeen** [comment]
WMDA users definitely want this info and are the main users here in terms of requirements, so closing this ticket as won't do.
