### ISSUE TITLE
Fetch donor information in matching algorithm to avoid MPA fetching donors again 

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#728]
The matching algorithm already needs to query the donor store to fetch e.g. external donor code and registry info. 

Match prediction algorithm also queries the donor store for registry + ethnicity info - but if this was included in the matching results, we could remove the MPA -> Donor SQL queries, and save some time.

**Comment by zabeen** [comment]
> - If a match result donor cannot be found in the donor store, then code should not throw an exception but simply remove that donor from the result set before it is written

@IgorKupreychik I just [found this in the support README](https://github.com/Anthony-Nolan/Atlas/blob/f891ab775af2051e50815ea6ebeaf2c46e037a30/README_Support.md?plain=1#L103). It makes a good point that if a "donor not found" exception is thrown during matching, then retry logic will automatically re-run the search by which time the donor deletion update should have reached the matching db. That's probably we have not observed this issue in matching all this time. 

On that basis, I suggest we don't remove the donor from the result set, as that would mask syncing issues between donor store and matching db.

**Comment by zabeen** [comment]
### Testing Notes

* Run a search that is known to return donors, with match prediction ON  
  * Search should complete successfully
  * `ExternalDonorCode` should be populated for every donor object in the results
  * Most donors should be represented (i.e., have match probability values and `isDonorUnrepresented` should be `false`)

* Open the matching results file for the search request in the container `matching-algorithm-results`
  * For each match result:
    * `DonorType` should still be populated
    * New object,[ `MatchingDonorInfo`](https://github.com/Anthony-Nolan/Atlas/blob/a3a993d83cd68d064b1ffe78d02adf9dc64ae38a/Atlas.Client.Models/Search/Results/Matching/MatchingAlgorithmResult.cs#L103), should be present and populated
