### ISSUE TITLE
Support 2-field alleles for some haplotype frequency sets 

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#746]
Atlas currently supports two resolutions of HF set data: 

* g-group 
* G-group

This issue involves adding support for a third resolution type, 2-field alleles. 

I believe this is the resolution that NMDP use for their own match prediction algorithm, and may only be possible for donor pools with high enough resolution donors.

**Comment by zabeen** [comment]
No-one (namely, WMDA) has asked for this recently, will re-create if needs be.
