### ISSUE TITLE
Match Prediction Functions app does not run match prediction 

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#749]
Currently it's very confusing that the match prediction functions app does not actually run match prediction - only HF set import, and debug endpoints for internal aspects of the algorithm.

We could fix this in multiple ways: 

* Move the durable functions layer to the match prediction app
  *  This is likely quite a lot of work
  * We also need to consider whether this is acceptable for searches that are run without match prediction - as it would mean the match prediction orchestration layer doesn't necessarily actually run match prediction.
* Rename the current match prediction app to be more meaningful - e.g. `MATCH-PREDICTION-FREQUENCY-SET-IMPORT` or similar

**Comment by zabeen** [comment]
There is now an endpoint that allows processing of match prediction requests outside of a search (intended use is for processing of large validation datasets), so closing this ticket.
