### ISSUE TITLE
Update search interface to support donor type in WMDA preferred format

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#757]
In the Donor JSON the donorType is “D” or “C” whereas the SearchDonorType is 1 or 2  (or Adult and Cord). This is inconsistent, but manageable. 

We shouldn't break compatibility with other integrations by renaming Adult and Cord for this purpose - but we can make it so "D" deserialises to "Adult", and "C" to "Cord"

**Comment by zabeen** [comment]
Now Atlas is integrated and live in WMDA, there's not much point implementing this change, as it would involve a code change on their system too!
