### ISSUE TITLE
Add appropriate indexes for selection + deletion of donors added before a certain cut off

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#761]
When WMDA want to run a full donor import, (which they intend to do every so often to ensure everything is in sync) - they will

(a) run a full import, having any donors that already exist replaced
(b) query the database to see which donors exist in the atlas database but were not included in the full update
(c) manually delete such donors

This process could eventually be automated as part of the job, but this card is just to ensure we have appropriate indexes to make this compromise solution feasible on a large dataset.

**Comment by zabeen** [comment]
Now we have donor-checker functionality in place which allows WMDA to check which donors are present, missing, or have different HLA than expected, periodic full loads are not necessary (and subsequent clean up) are not necessary.
