### ISSUE TITLE
Resolve build warnings

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#772]
These are the warnings (and their counts) left on the solution after the clean up performed as part of :

Could not evaluate 'Microsoft.Win32.Registry.dll' for extension metadata. Exception message: Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Warning count: 2

NU1608	Detected package version outside of dependency constraint: Microsoft.NET.Sdk.Functions 1.0.28 requires Newtonsoft.Json (= 11.0.2) but version Newtonsoft.Json 12.0.2 was resolved. Warning count: 2

Warnings not listed above have either been assigned their own task, as they were deemed resolvable in the short term (they are all linked to the original task, ), or they are warnings that have been introduced by new dev, and should be investigated.

_____________________

# Requirements 
- The warning count of the project is 0

**Comment by zabeen** [comment]
Covered by #1284
