### ISSUE TITLE
Send alerts via service bus topics if any dead lettered messages are detected

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#786]
Aim to use terraform to set up all alerting such that it's automatically set up for all envs. 

We may want to use event grid to hook dead letter alerts up to sending appropriate service bus messages. 

If this doesn't prove possible within purely terraformed resources, we should leave detailed set up instructions in the repo documentation.

**Comment by zabeen** [comment]
We are using dead-letter queue listener functions to re-route dead letters to where we want them to go.
