### ISSUE TITLE
As an admin, I want to simplify the donor import file schema, so that it can better handle mixed DNA/serology locus typings

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#839]
**Description**
Current donor import file schema for a locus HLA typing is:
```
"hla": {
  "locus_name": {
          "dna": {
              "field1": "nullable string",
              "field2": "nullable string"
          },
          "ser": {
              "field1": "nullable string",
              "field2": "nullable string"
          }
      }
}
```

Due to validation rules about `field 1` not being empty if `field 2` is populated, there is no way to submit a locus typing where one field is DNA typed and the second field is serology typed. Though these typings are strange, there are a significant number of them in the AN live database. Right now both typings are being submitted in the `dna` field which is far from ideal.

Atlas has the ability to determine what kind of typing has been submitted, and only stores two field values per locus (it ignores any serology values where DNA is also submitted); and it does not use serology as a search determinant. Therefore, I propose to simplify the locus typing schema as follows:
```
"hla": {
  "locus_name": {
          "field1": "nullable string",
          "field2": "nullable string"
      }
}
```

**Risks**
As this is a change to a schema, it will be a breaking change unless schema versioning is used, and multiple schemas are supported at once.

**Component(s) to enhance (if known)**
- Donor Import

**Business value (select one or more):**
- Improved user experience

**How would this enhancement provide this value?**
Schema change would allow mixed typings to be submitted.

**Acceptance Criteria**
Given a donor import file where a donor has both serology and DNA typings at the same locus,
When the file is added to the azure blob storage container for upload,
Then the donors are imported without error, 
And the HLA typings are stored in the donor store database correctly,
And there are no HLA validation errors raised when the donor update is sent to the matching algorithm.

[Regression]
Given a donor import file where a donor has only DNA typing at a locus,
When the file is added to the azure blob storage container for upload,
Then the donors are imported without error, and the HLA typings are stored in the donor store database correctly,
And there are no HLA validation errors raised when the donor update is sent to the matching algorithm.

[Regression]
Given a donor import file where a donor has only serology typing at a locus,
When the file is added to the azure blob storage container for upload,
Then the donors are imported without error, and the HLA typings are stored in the donor store database correctly,
And there are no HLA validation errors raised when the donor update is sent to the matching algorithm.

**Required By Date**
Required sometime in December 2022, ahead of Atlas integration into WMDA.

**Comment by zabeen** [comment]
Submitted to @mmelchers for approval as WMDA were the end-users who initially designed the schema.

**Comment by mmelchers** [comment]
To be honest I do not see the benefit of this feature. We have our HLA data separated in DNA data and serology data. All data we have is sent to the matching engines. They can then determine which data gets used. 

To me it seems a lot better to keep it the way it as. This is for two reasons: 

1. The requested change would mean not-insignificant code changes on our end
2. It would add unnecessary complexity to our system because the different matching engines now have different input files. 

To me it would seem better to fix the source data rather than improve the dealing with bad data. The Anthony Nolan donors are already being sent to us in a correct format, so there already is a way of dealing with it on the side of Anthony Nolan.

**Comment by zabeen** [comment]
Thanks for response @mmelchers.

I appreciate your points about keeping things in sync, and not altering a schema because of dodgy data! But I still feel it is worth making this change for other more significant reasons (which I should have better emphasised in my request).

>  We have our HLA data separated in DNA data and serology data
If I am not mistaken, the reason the data is stored this way is because, historically, search algorithms (including AN's own legacy algorithm) used "equivalent serology" as search determinants when matching. AFAIK, modern algorithms do not use serology, in keeping with the [2011 WMDA framework for the implementation of HLA matching programs in hematopoietic stem cell donor registries and cord blood banks](https://pubmed.ncbi.nlm.nih.gov/20531286/).

Of course, it would be a significant task to overhaul WMDA's storage of HLA typing - not asking you to do that! - but I would not be surprised if you do eventually stop asking for equivalent serology from your member registries, as neither HAP-E nor Atlas need this data, nor would any other algorithm encoded to the latest guidelines.

I believe the schema should reflect the way the algorithm works, and not ask for data that is not required - it is misleading to request serology data separately when it is not used as a search determinant,

However, I completely understand your points, and I believe the compromise solution is to add a second version of the schema, with the cleaner layout, whilst still supporting the original version to make life easier for the upcoming integration work.

I hope this is satisfactory.

**Comment by zabeen** [comment]
Attempted to add an additional version of the schema, whilst also maintaining support for v1, but it requires too many modifications to the existing test suite to make it feasible at this stage. A smaller scale change is advised, e.g., adding new fields to HLA object, without removing the existing dna/ser fields.
