### ISSUE TITLE
Ability to compare presence or absence of donors/CBUs in WMDA donor set with ATLAS

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#878]
**Title**
As a PO of WMDA Search and Match I want to be sure that all donors in the WMDA database are present also in the ATLAS database and that there are no donors in ATLAS that should not be there. That way I can ensure that all relevant donors are considered for matching. 
**Description**
Currently there is a full initial load of donors from the WMDA database to the ATLAS database. Some donors/CBUs may be refused at that point. Additionally there are regular smaller differential updates. If one of those updates is somehow missed it could also lead to the ATLAS database being not fully synchronised to the WMDA database. 

For Hap-E we have solved it the following way: 
WMDA delivers a JSON file with ALL recordIds (which would be imported as the "DonorCode" in the ATLAS database) in a specified format. This is produced and sent to Hap-E per combination of donPool and donorType

example: 

`{
    "checkingMode": "listof donors",
    "donPool": 9778,
    "donorType": "D",
    "donors": [
        6240528013,
        6240528155,
        6240528435,
        6240528750,
        6240528961
    ]
}`

JSON schema: 
`{
	"type": "object",
	"$schema": "http://json-schema.org/draft-06/schema#",
	"properties": {
		"checkingMode": {
			"type": "string",
			"enum": [ "listof donors" ]
		},
		"donPool": {
			"type": "integer"
		},
		"donorType": {
			"type": "string",
			"enum": [ "D", "C" ]
		},
		"donors": {
			"type": "array",
			"items": {
				"type": "integer"
			}
		}
	},
	"required": [ "checkingMode", "donPool", "donors", "donorType" ],
	"additionalProperties": false
}`

A report is then generated by Hap-E indicating which recordId's are in their DB but should not be and which recordIds are missing. 

WMDA can then regenerate diff files for those donors to bring back the donors in sync. 

This ticket is just for checking whether the correct donors/CBUs are present. Not whether the typing is correct. 
 

**Component(s) to enhance (if known)**
unsure

**Business value (select one or more):**
- Improved user experience
- Improved supportability
- Improved resilience

**How would this enhancement provide this value?**
By making sure the ATLAS database is in sync with that of WMDA, we can be sure that all donors that would be expected in search results are in the search results. 

**Acceptance Criteria**
GIVEN the feature is in place
WHEN A list of recordId's is provided for a donPool & donorType combination
THEN ATLAS provides output indicating which recordId's should be removed and which should be added. 

**Required By Date (if any)**
When in production, we need to be sure that the right donors are present in ATLAS database. So required around full public production date in Search & Match or soon after.

**Comment by zabeen** [comment]
@mmelchers @WMDAJesse 

Please could you confirm how many donor IDs you expect to check at a time? What is the maximum? E.g., 10s of thousands, or worse case, all 30 million donors in WMDA registry?

**Comment by mmelchers** [comment]
The largest IONs have about 9 million donors currently. So if we keep future growth into account then let's say the largest file would be below 15 million.

**Comment by zabeen** [comment]
general q, is there a reason to split this work out from the [second ticket](https://github.com/Anthony-Nolan/Atlas/issues/879), as the second one will also tell you that a donor diff needs to be sent out, if the donor is absent?

**Comment by mmelchers** [comment]
the second ticket would not tell me that a donor needs to be deleted. Also the second task is likely to be much heavier on the database so we do the lightweight check first. For instance due to the way Japanese donors do not have ANY identifiers, we send ATLAS the complete set of donors in a diff file (about half a million donors) and then we may need to use this feature to delete all previous half a million donors. I leave it up to you though.

**Comment by zabeen** [comment]
Ok, that makes sense, we will stick to leaving it as two separate features then.

**Comment by zabeen** [comment]
## High-Level Design

### Input
- The json input file need only contain a string array of donors IDs, i.e.,
```
{
    "recordIds": [
        "6240528013",
        "6240528155"
    ]
}
```
- As it's a very different input schema and journey to donor import, we should place the file in a different location.
  - Could possibly use the same storage container and a dedicated subfolder, e.g., `donors/donor-id-checker/`
  - In this case, the [filter on the Donor Import Event Grid sub](https://github.com/Anthony-Nolan/Atlas/blob/master/terraform/core/modules/donor_import/event_grid.tf) would need modifying, and a new event grid sub set up for the donor id file.
  - Useful links:
    - https://stackoverflow.com/questions/70951359/how-to-define-a-dynamic-block-for-advanced-filter
    - https://learn.microsoft.com/en-us/azure/event-grid/event-filtering#advanced-filtering
    - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventgrid_event_subscription
- Will also need to [terraform a new service bus topic and sub](https://github.com/Anthony-Nolan/Atlas/blob/master/terraform/core/modules/donor_import/servicebus.tf) for the donor id check request message.

### Output
- Equally simple output:

```
{
    "results":[
        {
            "RecordId": "6240528013",
            "IsPresentInDonorStore": true
        },
        {
            "RecordId": "6240528155",
            "IsPresentInDonorStore": false
        }
    ]
}
```

### DonorImport.Function
- Add new SBT function subscribed to the new donor import checker topic.
- Pass blob stream to donor id checker service (need to stream blob as it could contains 100s of thousands of ids).

### DonorImport.Data
- Use/extend donor read repository with donor id checker functionality.

### DonorImport
- Use/extend donor read service with donor id checker functionality.
- Recommend reading donor ids from stream in batches to minimise memory footprint.

**Comment by zabeen** [comment]
Currently blocked for testing by #879 - waiting for donor count to be added to the results notification message.

**Comment by zabeen** [comment]
## Test Cases

### Present Donors only

Given a donor id checker input file of valid schema  
That contains a list of record ids that are **present** in the Atlas donor store  
When the file is dropped into the `donors/donor-id-checker` subfolder  
Then a new message is placed on the `donor-id-checker-requests` topic  
And after processing, a new message is written to `donor-id-checker-results` topic that will have a absent donor count of `0`  
And the results message will have no results file name.  

### Absent Donors only

Given a donor id checker input file of valid schema  
That contains a list of record ids that are **absent** from the Atlas donor store  
When the file is dropped into the `donors/donor-id-checker` subfolder  
Then a new message is placed on the `donor-id-checker-requests` topic  
And after processing, a new message is written to `donor-id-checker-results` topic that will have the expected absent donor count  
And the results message will have a results file name  
And the results file will list all the record Ids of the absent donors (order not important).  

### Mix of Present and Absent Donors

Given a donor id checker input file of valid schema  
That contains a list of record ids, some of which are present in the Atlas donor store and remaining of which are absent  
When the file is dropped into the `donors/donor-id-checker` subfolder  
Then a new message is placed on the `donor-id-checker-requests` topic  
And after processing, a new message is written to `donor-id-checker-results` topic that will have the expected absent donor count    
And the results message will have a results file name  
And the results file will only list the record Ids of the absent donors (order not important) and none of the present donors.    

### Exception Testing

Given a donor id checker input file of **invalid** schema  
When the file is dropped into the `donors/donor-id-checker` subfolder  
Then a new message is placed on the `donor-id-checker-requests` topic  
And after processing, a new message is written to the `Alerts` topic stating that the donor-id-checker input file is invalid  
And the details of the exception will be logged to Application Insights  
And no message is written to `donor-id-checker-results` topic.  


Given a **donor import** file of valid schema  
When the file is dropped into the `donors/donor-id-checker` subfolder  
Then a new message is placed on the `donor-id-checker-requests` topic  
And after processing, a new message is written to the `Alerts` topic stating that the donor-id-checker input file is invalid  
And the details of the exception will be logged to Application Insights  
And no message is written to `donor-id-checker-results` topic.  


Given a donor id checker input file of valid schema  
That contains a list of record ids  
When the file is dropped into the `donors/donor-id-checker` subfolder  
And a transient exception occurs during message processing  
Then the request message will automatically be retried until the maximum delivery count is reached  
And the message will dead-letter.  

> Requirements Question: should the donor-id-checker results message have a completion status property: `success`/`failed`, and if so, should dead-lettered messages be routed to the results topic, as we have done for #895? @WMDAJesse 


Given a donor id checker input file of valid schema  
That contains a list of record ids  
When the file is dropped into the top-level `donors` folder 
Then a new message is placed on the `donor-import-file-uploads` topic  
And after processing, a new message is written to the `Alerts` topic stating that the **donor import** input file is invalid  
And the details of the exception will be logged to Application Insights  
And no message is written to `donor-id-checker-results` topic.  


### Regression Testing

Given a **donor import** file of valid schema  
That contains a valid donor update  
When the file is dropped into the top-level `donors` folder 
Then a new message is placed on the `donor-import-file-uploads` topic  
And after processing, the donor update is successfully applied to the donor store.

**Comment by IgorKupreychik** [comment]
Dev Testing:

- Present Donors only - passed
- Absent Donors only - passed
- Mix of Present and Absent Donors - passed
- Exception Testing - passed
- Regression Testing - passed
