### ISSUE TITLE
Ability to compare HLA and other donor/CBU fields in WMDA donor set with that in ATLAS

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#879]
Title
As a PO of WMDA Search and Match I want to be sure that all values for donors/CBUs in the WMDA database that we send to ATLAS are the same in the ATLAS database. That way I can ensure that all relevant donors are considered for matching.
Description
Currently there is a full initial load of donors from the WMDA database to the ATLAS database. Some donors/CBUs may be refused at that point. Additionally there are regular smaller differential updates. If one of those updates is somehow missed it could also lead to the ATLAS database being not fully synchronised to the WMDA database.

For Hap-E we have solved it the following way:
WMDA delivers a JSON file with all information for each donor/CBU that we want to have in ATLAS. As with the full import this is split into several files per donPool/ donorType combination because for some donorPool's there are several million records and this would make the file to big. 

The file format is exactly the same as a full upload. We then tell Hap-E not to import the records, but to find them in its database, based on recordId (possibly in combination with donPool and donorType). 

A report is then generated by Hap-E indicating which recordId's differ in its database versus the provided info.

WMDA can then regenerate diff files for those donors/CBUs to bring back the donors in sync.

Component(s) to enhance (if known)
unsure

Business value (select one or more):

Improved user experience
Improved supportability
Improved resilience
How would this enhancement provide this value?
By making sure the ATLAS database is in sync with that of WMDA, we can be sure that all donors that would be expected in search results are in the search results.

Acceptance Criteria
GIVEN the feature is in place
WHEN A a file is provided in the full import format
AND it is provided in a way to trigger a synchronisation check and not an actual import
THEN ATLAS provides output indicating which recordId's contain data that is different in the ATLAS database versus the provided files

Required By Date (if any)
When in production, we need to be sure that the right donors are present in ATLAS database. So required around full public production date in Search & Match or soon after.

**Comment by zabeen** [comment]
@mmelchers @WMDAJesse 

Re: results file, we are thinking to keep things simple: a list of donor IDs, each with a `bool` property named something like "isIdenticalToInput" (name could change!), where if `true` that means the data in Atlas is same as submitted, and if `false` then that means the donor data is either different, or the donor is absent - either way, a diff update needs to be provided.

**Comment by mmelchers** [comment]
that would make sense

**Comment by zabeen** [comment]
@disaev-nmdp sorry for late notice, could you please manually edit the [donor import file schema with the new enum value](https://github.com/Anthony-Nolan/Atlas/blob/b204eb9a7dfa01771228ce5c3c8fdf7a5c3fcf45/Schemas/DonorUpdateFileSchema.json#L5)? And use the `Description field` to explain what the new enum value means (i.e., donors will not be imported, but the info in file will be checked against what is already stored in Atlas).

Please also add a new section to the [Donor Import README](https://github.com/Anthony-Nolan/Atlas/blob/master/README_DonorImport.md) briefly describing the new feature, its input, and output.
