### ISSUE TITLE
Indicate allele vs antigen mismatch

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#884]
**Title**
As a search coordinator I want to know whether a mismatch is an antigen or an allele mismatch. This is especially relevant for cord searches. 

**Description**
In WMDA Search and Match we need to indicate whether a mismatch is an antigen or allele mismatch. ATLAS currently does not provide that info so we always set it to "Antigen", which may confuse some search coordinators. Antigen vs allele mismatch should be based on serology. Please check this page on what should and should not be considered an antigen match: https://share.wmda.info/x/soAZGQ 

**Component(s) to enhance (if known)**
?

**Business value (select one or more):**
- Improved user experience

**How would this enhancement provide this value?**
Search coordinators are better able to determine the best cord search result. 

**Acceptance Criteria**
GIVEN a search in ATLAS has successfully finished
WHEN a certain record in the search results has a mismatch
THEN the type of mismatch (antigen vs allele) is indicated along with its position 

**Required By Date (if any)**
Please explain the significance of the date, if provided.
- E.g., "Required by \<date\> ahead of compliance inspection"

**Comment by zabeen** [comment]
@mmelchers is there a required by date for this issue?

**Comment by mmelchers** [comment]
@zabeen I am not sure. I know for some organisations it can be very important. It would definitely help adoption if this feature is present before we go live for everybody.

**Comment by zabeen** [comment]
## HLD

This involves [extending scoring](https://github.com/Anthony-Nolan/Atlas/tree/master/Atlas.MatchingAlgorithm/Services/Search/Scoring) to compare the equivalent serologies of patient-donor typings. The data needed to do this is already being extracted from the IMGT/HLA file, `rel_dna_ser`. So it should be a fairly isolated change to use that data within scoring to assess whether a P-group mismatched typing is antigen-matched.

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: ok
There is a new `isAntigenMatch` parameter in Search results of my requests


![Image](https://user-images.githubusercontent.com/107943429/235896741-b6626335-68cd-40a6-9e2c-ad26bf436785.png)

**Comment by zabeen** [comment]
As exercise 2 involved validation of this work, and change has been in UAT for some time, I am going to assume it is working as expected, and close this ticket. Any bugs regarding this feature can be raised as a new issue.
