### ISSUE TITLE
All non-completed searches should be in 1 place

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#895]
**Describe the bug**
Currently some searches that do not complete for some reason end up in the search-results-ready topic with a permanent failure. This is fine. In other instances searches are failing in a way that leads to no message appearing in the search-results-ready topic. For example they appear in the dead letter queue of the matching-requests topic. This should not be the case. All instances of failed searches should end up in 1 topic where it can be checked. The message should also contain information on where and why it failed.   

**To Reproduce**
1. Start many searches
2. check the search-results-ready topic over time

**Expected behaviour**
Search-results-ready topic contains a message for each failed and completed search. If search has failed, the place and reason for the failure is mentioned in the message. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44259052/222481548-9a1bc49b-af51-4dce-9ba7-f7d6365d3d18.png)

**Inputs/Outputs**

**Atlas Build & Runtime Info (please complete the following information):**

**Additional context**

**Comment by seanmobrien** [comment]
I am able to reliably reproduce this issue in WMDA's dev environment by sending the following search request:
`{"searchDonorType":"Adult","matchCriteria":{"donorMismatchCount":2,"locusMismatchCriteria":{"a":2,"b":2,"c":2,"dpb1":null,"dqb1":2,"drb1":2},"includeBetterMatches":true},"scoringCriteria":{"lociToScore":["Dpb1"],"lociToExcludeFromAggregateScore":[]},"searchHlaData":{"a":{"position1":"*01:01","position2":"*01:01"},"b":{"position1":"*08:01","position2":"*07:02"},"c":{"position1":"*07:01","position2":"*07:02"},"dpb1":{"position1":"*02:01","position2":"*87:01"},"dqb1":{"position1":"*02:01","position2":"*06:02"},"drb1":{"position1":"*03:01","position2":"*15:01"}},"patientEthnicityCode":null,"patientRegistryCode":null,"runMatchPrediction":true,"donorRegistryCodes":null}`

Sending this request to the Search API results in a message hitting the dead letter queue after 10 delivery attempts, and no search failure/error message.  There are no obvious fatal errors in logs when this occurs.  The last message on the trace is usually "Will match loci in the following order: Drb1, B, A, C".  An example SearchRequestId of a search where this issue occurred is 8d5110f2-8b9e-4948-8468-dc9379135483 .  

![Snag_6aa5327](https://user-images.githubusercontent.com/8743939/222834822-d000ef1a-abc6-4779-a889-f9b1026e3243.png)

The expectation is that if a search cannot complete for any reason, including getting stuck on a dead letter queue, a search failed message should be added to the search-results-ready topic indicating ATLAS is no longer processing the request.

**Comment by zabeen** [comment]
@WMDAJesse @mmelchers Would repeat search need this same enhancement, and would it be an MVP issue as well?

**Comment by mmelchers** [comment]
yes, it would also apply to repeat searches. It should apply to any search. It does not need to be in the MVP though as it is not essential for us to have repeat search capability right from the start for ATLAS.

**Comment by disaev-nmdp** [comment]
## Test Cases

Given a `ATLAS-MATCHING-ALGORITHM-FUNCTIONS` with incorrect connection string setting
When Search request is posted
Then message is placed to `matching-requests` topic
Then message is placed to Dead-letter queue
When `ATLAS-MATCHING-ALGORITHM-FUNCTIONS` connection string is set correctly
Then message is removed from `matching-requests` Dead-letter queue
Then message is placed to `search-results-ready` topic
