### ISSUE TITLE
Test that Atlas meets WMDA's Performance Requirements

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#906]
From @mmelchers 

**Donors (adult):**
0, 1, and 2 mismatches
There is a demand for 3 and 4 mismatch searches for donors, but this is not part of MVP.
expected time to run:
Hap-E has the following for searches with > 100 thousand potential 0 mismatch donors:
0 mismatch: median = 1016 seconds
1 mismatch: median = 1343 seconds
2 mismatch: median = 3788 seconds

So it would be reasonable for ATLAS to have the following:
0 mismatch: median < 2000 seconds
1 mismatch: median < 3000 seconds
2 mismatch: median < 7200 seconds

**Cords:**
In case of n/8 or n/10: 0, 1, 2, 3, and 4 mismatches
in case of n/6: 0, 1, and 2 mismatches
all cord searches in Hap-E (even with 4 mismatches and more than 50 thousand records) finish within 2500 seconds. The median is < 700

So for ATLAS:
any cord search with more than 50 thousand records: median < 1400 seconds

**Comment by zabeen** [comment]
blocked until #897 and #901 have been completed

**Comment by zabeen** [comment]
Note: This ticket is here to capture the NFRs for Atlas, but the actual testing would be done on WMDA dev, and so should be moved to the WMDA Testing column whenever it becomes unblocked.

**Comment by daria-sorokina-da** [comment]
Tests for 76 patients started at the same time:

- Match prediction batch size: 1000, 100, 10
- Max Concurrent Activity Functions: 10, 20, 40
- Matching Algorithm Batch Size: 10000, 1000, 100

**Comment by daria-sorokina-da** [comment]
Results:
- Match prediction batch size: 100, Max Concurrent Activity Functions: 10, Matching Algorithm Batch Size: 10000, Service Plan Tier: EP3 - **76 searches finished in 1h 3min**
- Match prediction batch size: 10, Max Concurrent Activity Functions: 10, Matching Algorithm Batch Size: 10000, Service Plan Tier: EP3 - **76 searches finished in 49min**
- Match prediction batch size: 10, Max Concurrent Activity Functions: 20, Matching Algorithm Batch Size: 10000, Service Plan Tier: EP3 - **76 searches finished in 1h 1min**
- Match prediction batch size: 10, Max Concurrent Activity Functions: 10, Matching Algorithm Batch Size: 1000, Service Plan Tier: EP3 - **76 searches finished in ???**

**Comment by zabeen** [comment]
currently blocked by #919 and #945

**Comment by zabeen** [comment]
@seanmobrien and @zabeen to document outcomes from WMDA parallel run onto an appropriate page on share space

**Comment by zabeen** [comment]
Closing as Atlas has been approved for production, though it would be good to benchmark current performance ahead of planned optimisations.
