### ISSUE TITLE
Reduce overall number of storage transactions

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#908]
Work on #902 has reduced the number of `CreateContainer` requests made during search, but there is room for further improvement to reduce the overall amount of storage transactions, which will further reduce cloud storage costs. The main points of storage interaction are uploading match prediction requests and downloading match prediction results.

1. Add a batch upload option to [BlobUploader](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Common/AzureStorage/Blob/BlobUploader.cs) to be used when [uploading match prediction batched requests](https://github.com/Anthony-Nolan/Atlas/blob/947174ba820f63dba64beb4d7092f118b799f0a6/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L87) and when [uploading donor match probability results](https://github.com/Anthony-Nolan/Atlas/blob/c676df9b5d74c715bfc2ddce92d223f9d5a6e138/Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithm.cs#L71). That way, the container's existence needs to only be checked once.
3. Add a batch download option to [BlobDownloader](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs) to be used when [downloading match prediction results](https://github.com/Anthony-Nolan/Atlas/blob/947174ba820f63dba64beb4d7092f118b799f0a6/Atlas.Functions/Services/ResultsCombiner.cs#L98). Could possibly use the [BlobContainerClient.GetBlobsAsync](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-list).

**Comment by zabeen** [comment]
FYI @IgorKupreychik The batch uploader could also be used when writing out search results to multiple files #897

**Comment by IgorKupreychik** [comment]
@zabeen I've already implemented BatchUpload and BatchDownload for #897, currently it's in my local branch since I'm still working on the ticket

**Comment by daria-sorokina-da** [comment]
For QA:
- run new search and check that results are returned

**Comment by DmitriyShcherbina** [comment]
New Search test status - Ok
