### ISSUE TITLE
Failed searches resulting in dead-letter message

### ISSUE THREAD

**Issue by seanmobrien** [Anthony-Nolan/Atlas#917]
**Describe the bug**
Failed searches result in a dead-letter message being added to the search-results-ready/atlas-searchfinished-subscriber subscription

**To Reproduce**
1. Run a search that encounters an error during the MatchingAlgorithm stage
2. Using service bus explorer, look at the search-results-ready/atlas-searchfinished-subscriber dead letter queue.  Observe new message in dead-letter queue.  Note the BlobStorageContainerName and ResultsFileName are null and failure info is non-null

**Expected behaviour**
search-results-ready/atlas-searchfinished-subscriber messages are successfully delivered, regardless of whether the search was successful

**Inputs/Outputs**
Sample dead-lettered message:
`{"FailureMessage":"Search failed at stage: Matching Algorithm. See Application Insights for failure details.","FailureInfo":{"StageReached":"Matching Algorithm","MatchingAlgorithmFailureInfo":{"ValidationError":null,"AttemptNumber":11,"RemainingRetriesCount":0},"WillRetry":false},"MatchingAlgorithmTime":"00:00:00","MatchPredictionTime":"00:00:00","OverallSearchTime":"00:00:00","SearchRequestId":"xxxxxxxxx","WasSuccessful":false,"RepeatSearchRequestId":null,"BlobStorageContainerName":null,"ResultsFileName":null,"NumberOfResults":null,"MatchingAlgorithmHlaNomenclatureVersion":null}`

**Atlas Build & Runtime Info (please complete the following information):**
 - Runtime Environment: Azure Cloud (WMDA)
 - Atlas Version: N/A
 - GitHub commit ID of Atlas build: **https://github.com/Anthony-Nolan/Atlas/commit/8b9ac325d2e0bbfdbc82763268df2b10131994cf**

**Comment by zabeen** [comment]
@seanmobrien I don't think this is an Atlas backlog issue, as Atlas doesn't consume messages on that sub. This is likely down to the WMDA function that is reading the messages - I can see the delivery count is 11 for last message. It's possibly due to messages being raised for searches that no longer exist on wmda side, that were generated during testing. Please could you copy this ticket over to wmda integration backlog?
