### ISSUE TITLE
Failed searches resulting in dead-letter message on repeat search sub of matching results topic

### ISSUE THREAD

**Issue by seanmobrien** [Anthony-Nolan/Atlas#918]
Describe the bug
Failed searches result in a dead-letter message being added to the matching-results-ready/repeat-search subscription

To Reproduce

Run a search that encounters an error.
Using service bus explorer, look at the matching-results-ready/repeat-search dead letter queue. Observe new message in dead-letter queue. Note the BlobStorageContainerName and ResultsFileName are null and failure info is non-null.  ArgumentNullExceptions are logged in AI.

![Snag_5cbd832](https://user-images.githubusercontent.com/8743939/227390095-e19625f1-c8e0-49a5-b595-970dba69d8c6.png)

Expected behaviour
matching-results-ready/repeat-search messages are successfully delivered, regardless of whether the search was successful

Inputs/Outputs
Sample dead-lettered message:
`{"SearchRequest":null,"IsRepeatSearch":false,"MatchingAlgorithmServiceVersion":"1.0.0.0","ElapsedTime":"00:00:00","ValidationError":null,"FailureInfo":{"ValidationError":null,"AttemptNumber":1,"RemainingRetriesCount":9},"SearchRequestId":"b3a533c6-6ee5-4c46-b085-db8a7637991b","WasSuccessful":false,"RepeatSearchRequestId":null,"BlobStorageContainerName":null,"ResultsFileName":null,"NumberOfResults":null,"MatchingAlgorithmHlaNomenclatureVersion":"3510"}`

Atlas Build & Runtime Info (please complete the following information):

Runtime Environment: Azure Cloud (WMDA)
Atlas Version: N/A
GitHub commit ID of Atlas build: https://github.com/Anthony-Nolan/Atlas/commit/8b9ac325d2e0bbfdbc82763268df2b10131994cf

**Comment by daria-sorokina-da** [comment]
Steps:
- search fails in Atlas
- a failed search message is added to repeat-search queue
- repeat search processor picks up this message and tries to load the results, which are not there, and fails

Expected result:
The repeat search processor should ignore these message with failure results, and not deadletter

**Comment by DmitriyShcherbina** [comment]
AN test status: OK

**Comment by zabeen** [comment]
I don't think this actually needs re-testing in WMDA environment as testing in AN Dev should be sufficient, so moving to Final Review column.
