### ISSUE TITLE
Report symmetric difference between WMDA donpool/donor type donor id set and Atlas set

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#919]
This issue covers functionality that was missed from #878.

WMDA will provide Atlas with a complete set of donor record IDs for a defined `donPool` and `donorType` combination. Atlas needs to then report the **symmetric difference** between the WMDA set and the set of record Ids it holds for the same `donPool+donorType` within the donor store, i.e.,:
- those record Ids listed in the WMDA set that are absent from Atlas store (already implemented as part of #878) and,
- those Ids in Atlas that are not in the WMDA set (to be implemented here).

## Input File Schema
```json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "properties": {
        "donPool": {
            "type": "string"
        },
        "donorType": {
            "type": "string",
            "enum": [
                "D",
                "C",
                "B"
            ],
            "description": "Donor, Cord or Banked"
        },
        "donors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "donPool",
        "donors",
        "donorType"
    ]
}
```

Note: small changes have been made to the schema shared in #878:
- `checkingMode` is not required and has been removed from the schema (but it should be ignored if provided in the input file)
- `donPool` and `donors` array have been changed from `integer` to `string` to be in line with the existing Atlas donor import schema

## Possible Output File Schema
Record ids will most likely be written to one file as below (the alternative is to write to two separate files, each containing a different subset of ids).

```json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "properties": {
        "donPool": {
            "type": "string"
        },
        "donorType": {
            "type": "string",
            "enum": [
                "D",
                "C",
                "B"
            ],
            "description": "Donor, Cord or Banked"
        },
        "absentRecordIds": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Donor ids submitted in checker input file that are absent from Atlas donor store for the submitted donPool and donorType"
        },
        "orphanedRecordIds": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Donor ids that are in Atlas donor store for the submitted donPool and donorType but are absent from the checker input file"
        }
    }
}
```

## Acceptance Criteria

Given a donor-id-checker file with valid schema  
containing a set of record Ids for a specifed donPool and donorType
And Atlas donor store set is identical to the submitted set
When the file is submitted to Atlas
Then Atlas will report that no ids are absent
And that there are no orphaned records.

Given a donor-id-checker file with valid schema  
containing a set of record Ids for a specifed donPool and donorType
And Atlas donor store set has missing ids when compared to the submitted set
When the file is submitted to Atlas
Then Atlas will report the absent record ids
And report there are no orphaned records.

Given a donor-id-checker file with valid schema  
containing a set of record Ids for a specifed donPool and donorType
And Atlas donor store set has ids that are not in the submitted set
When the file is submitted to Atlas
Then Atlas will report that no ids are absent
And report the orphaned record ids.

Given a donor-id-checker file with valid schema  
containing a set of record Ids for a specifed donPool and donorType
And Atlas donor store set has missing ids when compared to the submitted set
And also has ids that are not in the submitted set
When the file is submitted to Atlas
Then Atlas will report the absent record ids
And also report the orphaned record ids.

Given a donor-id-checker file with valid schema  
that contains an empty array of record ids for a specifed donPool and donorType
And Atlas donor store set does contain record ids
When the file is submitted to Atlas
Then Atlas will report that no ids are absent
And report the orphaned record ids.

Given a donor-id-checker file with valid schema  
that contains an empty array of record ids for a specifed donPool and donorType
And Atlas donor store set also has no ids
When the file is submitted to Atlas
Then Atlas will report that no ids are absent
And that there are no orphaned records.

Given a donor-id-checker file with a valid schema
That also has an additional property that is not defined in the schema (e.g., string property, `checkingMode` )
When the file is submitted to Atlas
Then Atlas will successfully process the file and not send out any alerts.

Given a donor-id-checker file with an **invalid** schema  
When the file is submitted to Atlas
Then Atlas will send out an Alert with details of the failed file upload.

**Comment by zabeen** [comment]
@mmelchers please check the issue description fits with your expectations, thanks!

**Comment by zabeen** [comment]
## HLD

* Extend input model for new props in input file
* Extend output notification message and file model with new props
* New donor reader repository method to query donor store by donPool (registryCode?) and donorType, returning a list of externalDonorCodes - compare returned set to input set, and report those Atlas ids not in original set (i..e, orphaned records).
* No need to make any API changes, other than the models.

**Comment by daria-sorokina-da** [comment]
@seanmobrien 
Could you please run a GROUP BY query in Donors table - grouping by donPool, donorType, and let us know what the maximum numbers are, and for which values?

**Comment by mmelchers** [comment]
the largest number we will be sending in the dev environment is 9011225 
in prod it will be similar but it can grow over time. 
this is for the 3553 - D combination.

**Comment by zabeen** [comment]
@disaev-nmdp can you please attach an example input file for this feature so that @DmitriyShcherbina can use it for testing? thanks

**Comment by disaev-nmdp** [comment]
@DmitriyShcherbina json files are not allowed to be attached, here is a content of the file
{
	"donPool": "1",
	"donorType": "D",
	"donors": [
                "donor-prefix-0",
                "abcent-donor-prefix-0",
		"donor-prefix-1",
		"abcent-donor-prefix-1"
    ]
}

**Comment by seanmobrien** [comment]
When testing with a sample WMDA input file, the following error is logged and causing the check process to be bypassed:

![Snag_20c02f90](https://user-images.githubusercontent.com/8743939/233718227-f3962481-bfad-407f-b927-6842f15036d3.png)

Requirements indicate the checkingMode property should be ignored if present
![Snag_20c094b2](https://user-images.githubusercontent.com/8743939/233718291-125425e4-1897-42cd-948f-bcdf8edf09ac.png)

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok
