### ISSUE TITLE
Register search services needed for repeat search without results uploader

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#924]
[Repeat search service config calls RegisterSearch method on matching service config](https://github.com/Anthony-Nolan/Atlas/blob/138492be4096385192dd0a06aed5d94bdf3738c3/Atlas.RepeatSearch/ExternalInterface/DependencyInjection/ServiceConfiguration.cs#L49) in order to register search related services needed for repeat search.

Matching registers a results uploader used by its SearchRunner. However, repeat search registers its own uploader as it is responsible for uploading results via [`RepeatSearchRunner`](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs).

This leads to a duplication of azure settings being registered within Repeat search service config.

Need to register search services, without search results uploader, for use by repeat search.

**Comment by daria-sorokina-da** [comment]
For QA:
- Need to run a new search and make sure it returns results
- Need to run a repeat search and make sure it returns results

**Comment by DmitriyShcherbina** [comment]
> For QA:
> 
> * Need to run a new search and make sure it returns results
> * Need to run a repeat search and make sure it returns results

New Search test status - Ok
Repeat Search test status - Ok
