### ISSUE TITLE
DPB1 typing with Null allele should be treated as homozygous during TCE group scoring

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#925]
**Describe the bug**
Patient typing at DPB1 had a null allele (`DPB1 *02:01, *64:01N`) and the donors in their search results were not scored for DPB1 match grade, instead they all had the assignment of `U`.

**To Reproduce**
1. Run a search request with DPB1 scoring enabled, with DPB1 excluded from aggregate scoring. DPB1 typing should contain one null-expressing allele (e.g., `DPB1 *02:01, *64:01N`) - the exact patient search HLA that triggered this ticket is available on request.
2. On completion of search, download the results file from blob storage.
3. Scroll down to a scoring result for a donor typed with DPB1, and you will see following:
```json
"Dpb1": {
                        "IsLocusMatchCountIncludedInTotal": false,
                        "MatchCategory": "Unknown",
                        "MatchCount": 0,
                        "IsLocusTyped": true,
                        "MismatchDirection": "NotApplicable"
                    }
```
5. AI Logs for search will also show the following message for each donor that had DPB1 typing: "Could not find patient TCE group pair: (3, ) in hardcoded DPB1 TCE group matching behaviour. Something has likely gone wrong, and the Unknown grade will be used until this is fixed."

**Expected behaviour**
Expect for null-containing DPB1 typings to be treated as if the patient (or donor, where applicable) is homozygous for the expressing allele, and the TCE groups to be calculated accordingly. 

**Inputs/Outputs**
Patient HLA and original search results available on request.

**Atlas Build & Runtime Info (please complete the following information):**
 - Runtime Environment - Anthony Nolan LIVE-ATLAS
 - Atlas Version - 1.4.2
 - GitHub commit ID of Atlas build - `stable/1.4.2` tag

**Additional context**
[Link to DPB1 TCE group calculator that needs to be extended with null-handling logic](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm/Services/Search/Scoring/Grading/Dpb1TceGroupMatchCalculator.cs)

**Comment by zabeen** [comment]
### Testing Notes

- Detailed testing of this fix can only really be done by a user experienced with DPB1 scoring, so that will have to wait until the fix has been released to AN UAT.
- However, @DmitriyShcherbina can do a simple test which is to re-run the same patient in AN dev (DPB1 scoring should be enabled, no need for match prediction) and just check that `Dpb1.MatchCategory` for matching donors typed with DPB1 do not say "Unknown". I will send the patient HLA via DM.

**Comment by DmitriyShcherbina** [comment]
@zabeen dev testing statuk: ok
In my test result `Dpb1.MatchCategoty` has `Mismatch` value



![Image](https://user-images.githubusercontent.com/107943429/234851370-d61bdd16-f163-4f96-b948-0110c34459bf.png)
