### ISSUE TITLE
Search results not being chunked during Repeat search

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#929]
Test failure reported by AN dev testing of #897
Matching results are being written out to multiple files, but the final `atlas-search-results` are not.

Preconditions:
set -ATLAS-REPEAT-SEARCH-FUNCTION AzureStorage:SearchResultsBatchSize > 0 (ex.2, Batching ON)
set -ATLAS-FUNCTIONS AzureStorage:ShouldBatchResults true (Bathing ON)

Steps to reproduce:
1. Run Search Request
2. Import few donors with HLA data that mathes HLA data in Search request in step 1
3. Run Repeat Search Request using Search Request identifier from step 1 as OriginalSearchId

Actual Result:
Repeat Search results aren't batched in `repeat-search-results` blob container
but in `repeat-search-matching-results` blob container repeat search results are bathed as expected

Expected Result:
Repeat Search results are batched in `repeat-search-results` blob container

**Comment by zabeen** [comment]
@DmitriyShcherbina to add details found during testing to allow replication of bug

**Comment by DmitriyShcherbina** [comment]
@IgorKupreychik I've added additional info and steps to reproduce for this issue

**Comment by IgorKupreychik** [comment]
@DmitriyShcherbina could you please share a searchId/repeatSearchId of your attempt?

**Comment by DmitriyShcherbina** [comment]
@IgorKupreychik Yep, here it is `b08a49ac-d2bb-4142-b34b-944d42338607`
