### ISSUE TITLE
PersistSearchResults failed: "Insufficient memory to continue the execution of the program."

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#931]
Details to follow

**Comment by zabeen** [comment]
Ticket raised from testing #897 on WMDA DEV

@seanmobrien to perform initial investigation and paste findings into ticket description
@IgorKupreychik to work on fix

**Comment by daria-sorokina-da** [comment]
From my investigation of the error that happened 31 March ~ 7 am UTC:
PersistSearchResults failed, and looks like the function stopped here - as "Download match prediction algorithm results" was never logged:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Functions/Services/ResultsCombiner.cs#L90

 Looks like this method - DownloadMatchPredictionResults - loads all match prediction results in memory to add them to the resulting JSON.
There were 443484 donor results to download during the failed run.

**Comment by zabeen** [comment]
Thanks @daria-sorokina-da , I think the simple solution is to restrict the scope of the combiner service to one matching results blob at a time:

for each result file:
- download blob from matching-results
- Download match prediction result blobs for donors in current result file
- Combine results
- Write out the combined results to atlas-search-results blob storage.

That would also mean we don’t need to explicitly chunk the final combined results ourselves, as the incoming result set is already chunked.

**Comment by daria-sorokina-da** [comment]
For QA:

- please run a search with match prediction with Batching OFF
-- make sure that matching-algorithm-results are written as one blob
-- make sure that match-prediction-results are written per donor
-- make sure that final results are batched are written as one blob

- please run a search with match prediction with Batching ON
-- make sure that matching-algirithm-results are written per batching
-- make sure that match-prediction-results are written per donor
-- make sure that final results are batched are written per the same batching as matching-algirithm-results
-- make sure that final results have correct matching and match prediction data

Config changes for batching:
- <env>-ATLAS-MATCHING-ALGORITHM-FUNCTIONS AzureStorage:SearchResultsBatchSize 0  (default in AN) or batch size
- <env>-ATLAS-MATCHING-ALGORITHM-FUNCTIONS AtlasFunction:AzureStorage:ShouldBatchResults false (default in AN) / true

**Comment by daria-sorokina-da** [comment]
Testing results:
- Search with Batching ON - succeeded
- Search with Batching OFF - failed, because the reulting file in atlas-search-results does not conatain the Results
