### ISSUE TITLE
Search results file in atlas-search-results blob container doesn't contain donors in "Results" array

### ISSUE THREAD

**Issue by DmitriyShcherbina** [Anthony-Nolan/Atlas#934]
**Preconditions:**
set <env>-ATLAS-MATCHING-ALGORITHM-FUNCTIONS AzureStorage:SearchResultsBatchSize 0 (Batching OFF)
set <env>-ATLAS-FUNCTIONS AzureStorage:ShouldBatchResults false (Bathing OFF)

**Steps to reproduce:**
1. Run Search request with `"runMatchPrediction": false` (Search request should return some list of donors in results)
2. Note searchIdentifier in Search request response
3. Go to `atlas-search-results` blob container
4. Find and open search results json file according to noted identifier in step 2
5. Look at "Results" array

**Actual Result:**
Search results file in `atlas-search-results` blob container doesn't contain donors in "Results" array
But search resu;ts file in `matching-algorithm-results` blob container contain donors in "Results" array

**Expected Result:**
Search results file in `atlas-search-results` blob container contains donors in "Results" array

![Image](https://user-images.githubusercontent.com/107943429/230120202-48b9c110-2df2-4acb-a25a-687797ecd4e7.png)

**Comment by DmitriyShcherbina** [comment]
@IgorKupreychik testing has failed
search results .json file wasn't publicated to `atlas-search-results` blob container
but it was created in `matching-algorithm-results` blob container
`searchIdentifier: "14267d48-abf8-4be1-80d7-880fadf30e7f"`

**Comment by IgorKupreychik** [comment]
@DmitriyShcherbina you ran it with "RunMatchPrediction": false, that's why it didn't even start the second stage. Please try again with "RunMatchPrediction": true

**Comment by zabeen** [comment]
@DmitriyShcherbina this was in regression testing column, and I saw a commit in git history for the fix. Can you please confirm the fix was tested and it passed? Thanks!

**Comment by DmitriyShcherbina** [comment]
@zabeen We had a discussion regarding behaviour discribed in this ticket and we figured out that in case of Search request with `"runMatchPrediction": false` - Search results .json file in `atlas-search-results` shouldn't contain "Results" array

And in case of Search request with `"runMatchPrediction": true` - Search results .json file in `atlas-search-results`  contains "Results" array
