### ISSUE TITLE
Find out the parameters used for searches of different types from WMDA system

### ISSUE THREAD

**Issue by daria-sorokina-da** [Anthony-Nolan/Atlas#939]
Please add a comment with variants of  parameters sent in the request for:

- Donor search, 0 mismatches
- Donor search 1 mismatch
- Donor search 2 mismatches
- Cord search 0 mismatches
- Cord search 2 mismatches

```
{
    "SearchDonorType": "{{searchDonorType}}",
    "MatchCriteria": {
      "DonorMismatchCount": {{overall_mismatches}},
      "LocusMismatchCriteria": {
        "A": {{overall_mismatches}},
        "B": {{overall_mismatches}},
        "C": {{overall_mismatches}},
        "Dpb1": null,
        "Dqb1": {{overall_mismatches}},
        "Drb1": {{overall_mismatches}}
      },
      "IncludeBetterMatches": false
    },
    "ScoringCriteria": {
      "LociToScore": [
        "A",
        "B",
        "C",
        "Dqb1",
        "Drb1"
      ],
      "LociToExcludeFromAggregateScore": []
    },
    "SearchHlaData": {
      "A": {
        "Position1": "{{a_1}}",
        "Position2": "{{a_2}}"
      },
      "B": {
        "Position1": "{{b_1}}",
        "Position2": "{{b_2}}"
      },
      "C": {
        "Position1": "{{c_1}}",
        "Position2": "{{c_2}}"
      },
      "Dqb1": {
        "Position1": "{{dqb1_1}}",
        "Position2": "{{dqb1_2}}"
      },
      "Drb1": {
        "Position1": "{{drb1_1}}",
        "Position2": "{{drb1_2}}"
      }
    },
    "PatientEthnicityCode": null,
    "PatientRegistryCode": null,
    "RunMatchPredictions": true,
    "DonorRegistryCodes": null
}
```

We need to know these parameters to run the searches for the following patients:
[peak hour searches - all.csv](https://github.com/Anthony-Nolan/Atlas/files/11211861/peak.hour.searches.-.all.csv)

**Comment by mmelchers** [comment]
@daria-sorokina-da could you please explain what you mean? Which parameters are not in the provided file?

**Comment by daria-sorokina-da** [comment]
@mmelchers @IgorKupreychik 
In the file we have only:
- search_type - corresponds to SearchDonorType in the Atlas search request
- overall_mismatches - corresponds to MatchCriteria.DonorMismatchCount
- a_1..dqb1_2 - correspond to SearchHlaData

We also know that RunMatchPredictions is set as true for WMDA.

We need to know the values for:
- MatchCriteria.LocusMismatchCriteria
- ScoringCriteria
- PatientEthnicityCode 
- PatientRegistryCode
- DonorRegistryCodes

**Comment by mmelchers** [comment]
@daria-sorokina-da I have also added the request body to the share page: https://share.wmda.info/x/vQUgG

**Comment by daria-sorokina-da** [comment]
@mmelchers Thanks!
