### ISSUE TITLE
Write out search start times

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#945]
[SearchResultSet](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Client.Models/Search/Results/ResultSet/SearchResultSet.cs) currently lists time spans for matching algorithm and match prediction, which are useful for performance testing.

Now need to add the times that matching and match prediction actually began, to have insight into queuing and also to provide a cutoff datetime to repeat search requesters.

**Comment by zabeen** [comment]
### HLD

Have decided to write out log files to results containers containing the performance info, so we can include the time taken to write search results and send out notifications.

New log file will be named: `{search-request-id}-log.json` and the notification message will be extended with this name (e.g., `LogFileName`).

Two files to be written:
1) matching -> `matching-algorithm-results` container
2) search -> `atlas-search-results` container

Performance metrics will included:
- request initiation time
- processing start time
- completion time

Note: Some of this info is being logged to AI, but the downsides are that AI will not hold onto this data long term, and sometimes it performs sampling and filtering. This way the consumer can revisit the logs at their leisure, and download to their own db for performance analysis.

**Comment by zabeen** [comment]
Scope for this ticket is initial search, not repeat search. If performance needs to be logged for repeat search, we will do that work under a separate ticket.

**Comment by zabeen** [comment]
### Testing Notes

- Run a search with match prediction ON - make a note of the datetime the search was submitted and the time the completion notification message was published
- After completion, check containers: `matching-algorithm-results` and `atlas-search-results` - they should each contain a log file that is named `<search-request-id>-log.json`
- Each log file should contain the search request id, and performance metrics ([see this model](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Client.Models/Search/Results/RequestPerformanceMetrics.cs) for what metrics should be written out).
- Check the values in the log file against the datetimes noted in step 1 - the total duration (i.e., duration logged in matching log + duration logged in search-results log) should approximately equal the difference between the two datetimes.
- Sense check the various logged datetimess: i.e., initiation time should value less than start time, and start time less than completion time.

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok


![Image](https://user-images.githubusercontent.com/107943429/236431289-5fc439f5-4f7a-43ec-ac14-cbf9fda6cf86.png)

**Comment by zabeen** [comment]
@DmitriyShcherbina could you please paste screenshots of both log files? Many thanks!

**Comment by DmitriyShcherbina** [comment]
@zabeen Oh, sorry - sure.
Previous screenshot was from `atlas-search-results` and this one from `matching-algorithm-results`


![Image](https://user-images.githubusercontent.com/107943429/236437885-8440174b-67c7-41bf-8b7f-7bb9e6c1595a.png)
