### ISSUE TITLE
Add matching start time to search result summary

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#953]
The matching start time (specifically, the time the `matching-request` was picked up for processing) is needed by Atlas consumers for repeat search, to be used as the cut-off datetime.

It should be added to the search result summary file via the [`ResultSet` model](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs).

See solution to #945 as matching start time is being logged there.

It should be written for both original search requests and repeat search requests.

**Comment by zabeen** [comment]
Blocked by #945

**Comment by zabeen** [comment]
### Testing Notes

- Run a search request with match prediction ON
- Check the results summary file in `matching-results` and `atlas-search-results`:
  - They should both contain the property `MatchingStartTime`
  - The timestamp in both files should be identical
  - The start time should be equal to the `StartTime` written to the matching log file (`matching-results/<search-id>-log.json`)

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/2a749e72-d34b-4336-ab70-0f92eaa027c9)

**Comment by zabeen** [comment]
FYI @mmelchers - if you want to make a note of this new prop (`MatchingStartTime`) for when we eventually start integrating repeat search.
