### ISSUE TITLE
Search-aware logging should be used at all stages of search

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#956]
**Describe the bug**
When I run the AI query that looks for traces and events by atlas search request ID, I do not see all the expected log entries for the durable functions portion of the search. Specifically, most entries are from `RunMatchPredictionBatch` and `RunSearch`, but not the other activity functions, such as `PersistSearchResults`.

**To Reproduce**
1. Run any search with match prediction enabled, and wait until it has completed with success.
2. Open Application Insights in Azure and run the following query:
```
traces  
|union customEvents
|union exceptions
| where customDimensions["SearchRequestId"]=="paste-atlas-search-request-id-here"
| project operation_Name
| summarize by operation_Name
```
You will likely only see `RunMatchPredictionBatch` and `RunSearch` listed
3. Run AI query with the appropriate time frame for your search:
```
traces  
|union customEvents
|union exceptions
| where cloud_RoleName == "wmda-dev-atlas-functions" and operation_Name startswith "Persist"
| project operation_Name, id = tostring(customDimensions["SearchRequestId"]), message
```
You will see some log entries with a search id, but most will not have one.

**Expected behaviour**
All search-related logs should be findable by atlas search request id.

**Atlas Build & Runtime Info (please complete the following information):**
 - Runtime Environment: WMDA-DEV-ATLAS
 - Atlas Version: 1.6.0

**Comment by zabeen** [comment]
### Testing Notes

1) Run a search with match prediction switched ON
2) 10 mins after search has completed, open application insights and run the following query:
```
traces  
| union customEvents
| union exceptions
| where customDimensions["SearchRequestId"]=="paste-atlas-search-request-id-here"
| project operation_Name
| summarize by operation_Name

```

Expected result: should see logs for every stage of search (especially match prediction), including all of the following activity functions
* `PersistSearchResults`
* `PrepareMatchPredictionBatches`
* `RunMatchPredictionBatch`

**Comment by DmitriyShcherbina** [comment]
@zabeen I got this result in AppInsights after my Search Request
Is this expected result for this task?


![Image](https://user-images.githubusercontent.com/107943429/236224428-a34efaa1-b07a-4b4e-b684-64adac0cd5a7.png)

**Comment by zabeen** [comment]
@DmitriyShcherbina  Yes, that looks good, thanks! Can you please also run the following query, I forgot to include the counts

```
traces  
| union customEvents
| union exceptions
| where customDimensions["SearchRequestId"]=="paste-atlas-search-request-id-here"
| order by timestamp desc
```

and paste a screenshot of the top 20 rows, so we can be sure the last steps of the search are being logged by ID, which was not happening before. Thanks!

**Comment by DmitriyShcherbina** [comment]
@zabeen yep, here it is


![Image](https://user-images.githubusercontent.com/107943429/236228921-cc9a5f22-8fe8-4f77-8169-417b7102c85d.png)

**Comment by zabeen** [comment]
Fantastic, LGTM :)
