### ISSUE TITLE
Same HF set message being processed multiple times

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#993]
Same message being processed multiple times causes import failures ("Cannot insert duplicate key row in object 'MatchPrediction.HaplotypeFrequencySets' with unique index 'IX_RegistryCode_And_EthnicityCode'...") which eats up space in the db.

I suspect this may be something to do with lock expiry on messages for long-running HF set imports, which makes the request message available again to other function instances.

**Comment by zabeen** [comment]
host.json

```"extensions": {
    "serviceBus": {
      "messageHandlerOptions": {
        "maxConcurrentCalls": 1,
        "maxAutoRenewDuration": "02:00:00"
      }
    }
  },
```

**Comment by zabeen** [comment]
### Testing

- send multiple identical messages to HF import topic for the same HF set file
- outcomes: 
  - no alerts should be published during import
  - should multiple rows in HF set table for same file name, all inactive except for one

**Comment by DmitriyShcherbina** [comment]
@zabeen Testing status: Ok
<img width="409" alt="image" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/9639e3ac-3fac-40cf-a12a-86e667c2a02c">
